/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.9 for AB1585. Copyright Airoha Inc. (C) 2015.
 * 2023-04-04 10:03:12:0590
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
