/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.6 for AB1577S. Copyright Airoha Inc. (C) 2015.
 * 2022-12-15 09:33:30:0663
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char HAL_UART0_TXD_PIN = 0;
const char HAL_UART0_TXD_PIN_M_GPIO = 0;
const char HAL_UART0_TXD_PIN_M_SPDIF = 1;
const char HAL_UART0_TXD_PIN_M_UART0_TXD = 3;
const char HAL_UART0_TXD_PIN_M_PWM0 = 4;
const char HAL_UART0_TXD_PIN_M_CLKO = 5;
const char HAL_UART0_TXD_PIN_M_TEST_P = 7;
const char HAL_UART0_TXD_PIN_M_DMIC1_CLK = 9;
const char HAL_UART0_TXD_PIN_M_DEBUGMON0 = 13;
const char HAL_UART0_TXD_PIN_M_usb_line_state0 = 14;


const char HAL_UART0_RXD_PIN = 1;
const char HAL_UART0_RXD_PIN_M_GPIO = 0;
const char HAL_UART0_RXD_PIN_M_SPI_MST0_CS0 = 1;
const char HAL_UART0_RXD_PIN_M_UART0_RXD = 3;
const char HAL_UART0_RXD_PIN_M_I2S_SLV0_CK = 4;
const char HAL_UART0_RXD_PIN_M_I2C0_SCL = 5;
const char HAL_UART0_RXD_PIN_M_DSP_JTMS = 6;
const char HAL_UART0_RXD_PIN_M_TEST_N = 7;
const char HAL_UART0_RXD_PIN_M_CLKO = 8;
const char HAL_UART0_RXD_PIN_M_DMIC1_DAT = 9;
const char HAL_UART0_RXD_PIN_M_EINT = 12;
const char HAL_UART0_RXD_PIN_M_DEBUGMON1 = 13;
const char HAL_UART0_RXD_PIN_M_usb_line_state1 = 14;


const char BSP_EINTKEY0_PIN = 2;
const char BSP_EINTKEY0_PIN_M_GPIO = 0;
const char BSP_EINTKEY0_PIN_M_SPI_MST0_CS0 = 1;
const char BSP_EINTKEY0_PIN_M_I2S_MST0_WS = 2;
const char BSP_EINTKEY0_PIN_M_UART1_TXD = 3;
const char BSP_EINTKEY0_PIN_M_I2S_SLV0_WS = 4;
const char BSP_EINTKEY0_PIN_M_I2C0_SDA = 5;
const char BSP_EINTKEY0_PIN_M_DSP_JRST = 6;
const char BSP_EINTKEY0_PIN_M_TEST_BUS = 7;
const char BSP_EINTKEY0_PIN_M_PAD_DFUNC_SFCS0 = 8;
const char BSP_EINTKEY0_PIN_M_DMIC0_DAT = 9;
const char BSP_EINTKEY0_PIN_M_SPDIF = 10;
const char BSP_EINTKEY0_PIN_M_PWM0 = 11;
const char BSP_EINTKEY0_PIN_M_EINT = 12;
const char BSP_EINTKEY0_PIN_M_DEBUGMON2 = 13;
const char BSP_EINTKEY0_PIN_M_usb_data_0 = 14;


const char BSP_EINTKEY1_PIN = 3;
const char BSP_EINTKEY1_PIN_M_GPIO = 0;
const char BSP_EINTKEY1_PIN_M_SPI_MST0_MISO = 1;
const char BSP_EINTKEY1_PIN_M_I2S_MST0_RX = 2;
const char BSP_EINTKEY1_PIN_M_UART1_RXD = 3;
const char BSP_EINTKEY1_PIN_M_I2S_SLV0_RX = 4;
const char BSP_EINTKEY1_PIN_M_I2C0_SCL = 5;
const char BSP_EINTKEY1_PIN_M_AP_JTMS = 6;
const char BSP_EINTKEY1_PIN_M_AUXADC3 = 7;
const char BSP_EINTKEY1_PIN_M_PAD_DFUNC_SOUT = 8;
const char BSP_EINTKEY1_PIN_M_DMIC0_CLK = 9;
const char BSP_EINTKEY1_PIN_M_DSP_JTMS = 10;
const char BSP_EINTKEY1_PIN_M_EINT = 12;
const char BSP_EINTKEY1_PIN_M_DEBUGMON3 = 13;
const char BSP_EINTKEY1_PIN_M_usb_data_1 = 14;


const char BSP_EINTKEY2_PIN = 4;
const char BSP_EINTKEY2_PIN_M_GPIO = 0;
const char BSP_EINTKEY2_PIN_M_SPI_MST0_MOSI = 1;
const char BSP_EINTKEY2_PIN_M_I2S_MST0_TX = 2;
const char BSP_EINTKEY2_PIN_M_SPDIF = 3;
const char BSP_EINTKEY2_PIN_M_I2S_SLV0_TX = 4;
const char BSP_EINTKEY2_PIN_M_I2C1_SCL = 5;
const char BSP_EINTKEY2_PIN_M_DSP_JTDO = 6;
const char BSP_EINTKEY2_PIN_M_CTP1_AUXADC2 = 7;
const char BSP_EINTKEY2_PIN_M_PAD_DFUNC_SIN = 8;
const char BSP_EINTKEY2_PIN_M_DMIC1_DAT = 9;
const char BSP_EINTKEY2_PIN_M_I2C0_SDA = 10;
const char BSP_EINTKEY2_PIN_M_PWM1 = 11;
const char BSP_EINTKEY2_PIN_M_EINT = 12;
const char BSP_EINTKEY2_PIN_M_DEBUGMON4 = 13;
const char BSP_EINTKEY2_PIN_M_usb_data_2 = 14;


const char BSP_EINTKEY3_PIN = 5;
const char BSP_EINTKEY3_PIN_M_GPIO = 0;
const char BSP_EINTKEY3_PIN_M_SPI_MST0_SCK = 1;
const char BSP_EINTKEY3_PIN_M_I2S_MST0_CK = 2;
const char BSP_EINTKEY3_PIN_M_UART1_RXD = 3;
const char BSP_EINTKEY3_PIN_M_I2S_SLV0_CK = 4;
const char BSP_EINTKEY3_PIN_M_I2C1_SDA = 5;
const char BSP_EINTKEY3_PIN_M_DSP_JTDI = 6;
const char BSP_EINTKEY3_PIN_M_CTP2_AUXADC1 = 7;
const char BSP_EINTKEY3_PIN_M_PAD_DFUNC_SFCK = 8;
const char BSP_EINTKEY3_PIN_M_DMIC1_CLK = 9;
const char BSP_EINTKEY3_PIN_M_I2C0_SCL = 10;
const char BSP_EINTKEY3_PIN_M_PWM2 = 11;
const char BSP_EINTKEY3_PIN_M_EINT = 12;
const char BSP_EINTKEY3_PIN_M_DEBUGMON5 = 13;
const char BSP_EINTKEY3_PIN_M_usb_data_3 = 14;


const char HAL_AUXADC_0_PIN = 6;
const char HAL_AUXADC_0_PIN_M_GPIO = 0;
const char HAL_AUXADC_0_PIN_M_SPI_MST0_MISO = 1;
const char HAL_AUXADC_0_PIN_M_I2S_MST0_MCLK = 2;
const char HAL_AUXADC_0_PIN_M_UART1_TXD = 3;
const char HAL_AUXADC_0_PIN_M_I2S_SLV0_WS = 4;
const char HAL_AUXADC_0_PIN_M_I2C0_SDA = 5;
const char HAL_AUXADC_0_PIN_M_AP_JTCK = 6;
const char HAL_AUXADC_0_PIN_M_AUXADC0 = 7;
const char HAL_AUXADC_0_PIN_M_UART0_RTS = 8;
const char HAL_AUXADC_0_PIN_M_DMIC0_DAT = 9;
const char HAL_AUXADC_0_PIN_M_DSP_JTCK = 10;
const char HAL_AUXADC_0_PIN_M_EINT = 12;
const char HAL_AUXADC_0_PIN_M_DEBUGMON6 = 13;
const char HAL_AUXADC_0_PIN_M_usb_rx_active = 14;


const char HAL_UART1_RXD_PIN = 7;
const char HAL_UART1_RXD_PIN_M_GPIO = 0;
const char HAL_UART1_RXD_PIN_M_SPI_MST0_CS0 = 1;
const char HAL_UART1_RXD_PIN_M_I2S_MST0_WS = 2;
const char HAL_UART1_RXD_PIN_M_UART1_RXD = 3;
const char HAL_UART1_RXD_PIN_M_UART1_TXD = 4;
const char HAL_UART1_RXD_PIN_M_I2C1_SDA = 5;
const char HAL_UART1_RXD_PIN_M_DSP_JTCK = 6;
const char HAL_UART1_RXD_PIN_M_COEX_W1_DAT = 7;
const char HAL_UART1_RXD_PIN_M_UART0_CTS = 8;
const char HAL_UART1_RXD_PIN_M_DMIC1_CLK = 9;
const char HAL_UART1_RXD_PIN_M_BT_EPA_ELNA_ANT_SEL = 10;
const char HAL_UART1_RXD_PIN_M_PWM3 = 11;
const char HAL_UART1_RXD_PIN_M_EINT = 12;
const char HAL_UART1_RXD_PIN_M_DEBUGMON7 = 13;
const char HAL_UART1_RXD_PIN_M_usb_mac_valid = 14;


const char BSP_EINTKEY4_PIN = 8;
const char BSP_EINTKEY4_PIN_M_GPIO = 0;
const char BSP_EINTKEY4_PIN_M_SPI_MST0_MISO = 1;
const char BSP_EINTKEY4_PIN_M_I2S_MST0_RX = 2;
const char BSP_EINTKEY4_PIN_M_UART0_RTS = 3;
const char BSP_EINTKEY4_PIN_M_PWM0 = 4;
const char BSP_EINTKEY4_PIN_M_I2C1_SCL = 5;
const char BSP_EINTKEY4_PIN_M_DSP_JTMS = 6;
const char BSP_EINTKEY4_PIN_M_SPDIF = 7;
const char BSP_EINTKEY4_PIN_M_AUDIO_EXT_SYNC_EN0 = 8;
const char BSP_EINTKEY4_PIN_M_DMIC1_DAT = 9;
const char BSP_EINTKEY4_PIN_M_BT_EPA_ELNA_CPS = 10;
const char BSP_EINTKEY4_PIN_M_PWM4 = 11;
const char BSP_EINTKEY4_PIN_M_EINT = 12;
const char BSP_EINTKEY4_PIN_M_DEBUGMON8 = 13;
const char BSP_EINTKEY4_PIN_M_usb_phy_clock = 14;


const char HAL_I2S_MST1_WS_PIN = 11;
const char HAL_I2S_MST1_WS_PIN_M_GPIO = 0;
const char HAL_I2S_MST1_WS_PIN_M_SPI_MST0_CS0 = 1;
const char HAL_I2S_MST1_WS_PIN_M_I2S_MST1_WS = 2;
const char HAL_I2S_MST1_WS_PIN_M_UART1_CTS = 3;
const char HAL_I2S_MST1_WS_PIN_M_I2S_SLV0_WS = 4;
const char HAL_I2S_MST1_WS_PIN_M_CLKO = 5;
const char HAL_I2S_MST1_WS_PIN_M_DSP_JRST = 6;
const char HAL_I2S_MST1_WS_PIN_M_COEX_W3_BT_PRI = 8;
const char HAL_I2S_MST1_WS_PIN_M_DMIC1_CLK = 9;
const char HAL_I2S_MST1_WS_PIN_M_BT_EPA_ELNA_CHL = 10;
const char HAL_I2S_MST1_WS_PIN_M_PWM5 = 11;
const char HAL_I2S_MST1_WS_PIN_M_EINT = 12;
const char HAL_I2S_MST1_WS_PIN_M_DEBUGMON11 = 13;
const char HAL_I2S_MST1_WS_PIN_M_usb_opmode0 = 14;


const char HAL_I2S_MST1_RX_PIN = 12;
const char HAL_I2S_MST1_RX_PIN_M_GPIO = 0;
const char HAL_I2S_MST1_RX_PIN_M_SPI_MST0_MISO = 1;
const char HAL_I2S_MST1_RX_PIN_M_I2S_MST1_RX = 2;
const char HAL_I2S_MST1_RX_PIN_M_UART1_RXD = 3;
const char HAL_I2S_MST1_RX_PIN_M_I2S_SLV0_RX = 4;
const char HAL_I2S_MST1_RX_PIN_M_I2C1_SDA = 5;
const char HAL_I2S_MST1_RX_PIN_M_DSP_JTDO = 6;
const char HAL_I2S_MST1_RX_PIN_M_CLKO = 7;
const char HAL_I2S_MST1_RX_PIN_M_BT_EPA_ELNA_CSD = 8;
const char HAL_I2S_MST1_RX_PIN_M_DMIC0_DAT = 9;
const char HAL_I2S_MST1_RX_PIN_M_PWM0 = 10;
const char HAL_I2S_MST1_RX_PIN_M_EINT = 12;
const char HAL_I2S_MST1_RX_PIN_M_DEBUGMON12 = 13;
const char HAL_I2S_MST1_RX_PIN_M_usb_opmode1 = 14;


const char HAL_I2S_MST1_MCLK_PIN = 13;
const char HAL_I2S_MST1_MCLK_PIN_M_GPIO = 0;
const char HAL_I2S_MST1_MCLK_PIN_M_SPI_MST0_MOSI = 1;
const char HAL_I2S_MST1_MCLK_PIN_M_I2S_MST1_MCLK = 2;
const char HAL_I2S_MST1_MCLK_PIN_M_UART1_TXD = 3;
const char HAL_I2S_MST1_MCLK_PIN_M_I2S_SLV0_TX = 4;
const char HAL_I2S_MST1_MCLK_PIN_M_I2C1_SCL = 5;
const char HAL_I2S_MST1_MCLK_PIN_M_UART1_RXD = 6;
const char HAL_I2S_MST1_MCLK_PIN_M_GPIO_PIP_SEL_0 = 8;
const char HAL_I2S_MST1_MCLK_PIN_M_DMIC0_CLK = 9;
const char HAL_I2S_MST1_MCLK_PIN_M_AP_JTCK = 10;
const char HAL_I2S_MST1_MCLK_PIN_M_EINT = 12;
const char HAL_I2S_MST1_MCLK_PIN_M_DEBUGMON13 = 13;


const char HAL_I2S_MST1_TX_PIN = 14;
const char HAL_I2S_MST1_TX_PIN_M_GPIO = 0;
const char HAL_I2S_MST1_TX_PIN_M_SPI_MST0_SIO2 = 1;
const char HAL_I2S_MST1_TX_PIN_M_I2S_MST1_TX = 2;
const char HAL_I2S_MST1_TX_PIN_M_UART0_RTS = 3;
const char HAL_I2S_MST1_TX_PIN_M_I2S_SLV0_CK = 4;
const char HAL_I2S_MST1_TX_PIN_M_I2C0_SDA = 5;
const char HAL_I2S_MST1_TX_PIN_M_UART1_RTS = 6;
const char HAL_I2S_MST1_TX_PIN_M_GPIO_PIP_SEL_1 = 8;
const char HAL_I2S_MST1_TX_PIN_M_DMIC1_DAT = 9;
const char HAL_I2S_MST1_TX_PIN_M_PWM6 = 11;
const char HAL_I2S_MST1_TX_PIN_M_EINT = 12;
const char HAL_I2S_MST1_TX_PIN_M_DEBUGMON14 = 13;
const char HAL_I2S_MST1_TX_PIN_M_usb_xcvr_sel0 = 14;


const char HAL_I2S_MST1_CK_PIN = 15;
const char HAL_I2S_MST1_CK_PIN_M_GPIO = 0;
const char HAL_I2S_MST1_CK_PIN_M_SPI_MST0_SIO3 = 1;
const char HAL_I2S_MST1_CK_PIN_M_I2S_MST1_CK = 2;
const char HAL_I2S_MST1_CK_PIN_M_UART0_CTS = 3;
const char HAL_I2S_MST1_CK_PIN_M_SPDIF = 4;
const char HAL_I2S_MST1_CK_PIN_M_I2C0_SCL = 5;
const char HAL_I2S_MST1_CK_PIN_M_UART1_CTS = 6;
const char HAL_I2S_MST1_CK_PIN_M_BT_EPA_ELNA_CPS = 7;
const char HAL_I2S_MST1_CK_PIN_M_GPIO_PIP_SEL_2 = 8;
const char HAL_I2S_MST1_CK_PIN_M_DMIC1_CLK = 9;
const char HAL_I2S_MST1_CK_PIN_M_PWM7 = 11;
const char HAL_I2S_MST1_CK_PIN_M_EINT = 12;
const char HAL_I2S_MST1_CK_PIN_M_DEBUGMON15 = 13;
const char HAL_I2S_MST1_CK_PIN_M_usb_xcvr_sel1 = 14;


const char HAL_I2C_MASTER_1_SDA_PIN = 16;
const char HAL_I2C_MASTER_1_SDA_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_1_SDA_PIN_M_SPI_MST0_CS0 = 1;
const char HAL_I2C_MASTER_1_SDA_PIN_M_I2S_MST0_MCLK = 2;
const char HAL_I2C_MASTER_1_SDA_PIN_M_UART1_RXD = 3;
const char HAL_I2C_MASTER_1_SDA_PIN_M_UART2_RXD = 4;
const char HAL_I2C_MASTER_1_SDA_PIN_M_I2C1_SDA = 5;
const char HAL_I2C_MASTER_1_SDA_PIN_M_SPI_MST0_SIO2 = 6;
const char HAL_I2C_MASTER_1_SDA_PIN_M_BT_EPA_ELNA_CRX = 7;
const char HAL_I2C_MASTER_1_SDA_PIN_M_GPIO_PIP_SEL_3 = 8;
const char HAL_I2C_MASTER_1_SDA_PIN_M_DMIC0_DAT = 9;
const char HAL_I2C_MASTER_1_SDA_PIN_M_AP_JTMS = 10;
const char HAL_I2C_MASTER_1_SDA_PIN_M_EINT = 12;
const char HAL_I2C_MASTER_1_SDA_PIN_M_DEBUGMON0 = 13;


const char HAL_I2C_MASTER_1_SCL_PIN = 17;
const char HAL_I2C_MASTER_1_SCL_PIN_M_GPIO = 0;
const char HAL_I2C_MASTER_1_SCL_PIN_M_SPI_MST0_CS1 = 1;
const char HAL_I2C_MASTER_1_SCL_PIN_M_I2S_MST0_TX = 2;
const char HAL_I2C_MASTER_1_SCL_PIN_M_UART1_TXD = 3;
const char HAL_I2C_MASTER_1_SCL_PIN_M_UART2_TXD = 4;
const char HAL_I2C_MASTER_1_SCL_PIN_M_I2C1_SCL = 5;
const char HAL_I2C_MASTER_1_SCL_PIN_M_SPI_MST0_SIO3 = 6;
const char HAL_I2C_MASTER_1_SCL_PIN_M_BT_EPA_ELNA_CTX = 7;
const char HAL_I2C_MASTER_1_SCL_PIN_M_AUDIO_EXT_SYNC_EN1 = 8;
const char HAL_I2C_MASTER_1_SCL_PIN_M_DMIC0_CLK = 9;
const char HAL_I2C_MASTER_1_SCL_PIN_M_PWM8 = 11;
const char HAL_I2C_MASTER_1_SCL_PIN_M_EINT = 12;
const char HAL_I2C_MASTER_1_SCL_PIN_M_DEBUGMON1 = 13;
const char HAL_I2C_MASTER_1_SCL_PIN_M_usb_dm_pull_down = 14;


const char HAL_UART2_RXD_PIN = 20;
const char HAL_UART2_RXD_PIN_M_GPIO = 0;
const char HAL_UART2_RXD_PIN_M_SPI_MST0_MISO = 1;
const char HAL_UART2_RXD_PIN_M_I2S_MST0_WS = 2;
const char HAL_UART2_RXD_PIN_M_UART1_RXD = 3;
const char HAL_UART2_RXD_PIN_M_I2S_SLV0_WS = 4;
const char HAL_UART2_RXD_PIN_M_I2C1_SDA = 5;
const char HAL_UART2_RXD_PIN_M_BT_EPA_ELNA_CSD = 6;
const char HAL_UART2_RXD_PIN_M_COEX_W3_BT_WLAN = 7;
const char HAL_UART2_RXD_PIN_M_UART2_RXD = 8;
const char HAL_UART2_RXD_PIN_M_DMIC1_DAT = 9;
const char HAL_UART2_RXD_PIN_M_AUDIO_EXT_SYNC_EN0 = 10;
const char HAL_UART2_RXD_PIN_M_EINT = 12;
const char HAL_UART2_RXD_PIN_M_DEBUGMON4 = 13;
const char HAL_UART2_RXD_PIN_M_usb_da_idpullup = 14;


const char HAL_UART2_TXD_PIN = 21;
const char HAL_UART2_TXD_PIN_M_GPIO = 0;
const char HAL_UART2_TXD_PIN_M_SPI_MST0_MOSI = 1;
const char HAL_UART2_TXD_PIN_M_I2S_MST0_RX = 2;
const char HAL_UART2_TXD_PIN_M_UART1_TXD = 3;
const char HAL_UART2_TXD_PIN_M_I2S_SLV0_RX = 4;
const char HAL_UART2_TXD_PIN_M_I2C1_SCL = 5;
const char HAL_UART2_TXD_PIN_M_BT_EPA_ELNA_ANT_SEL = 6;
const char HAL_UART2_TXD_PIN_M_COEX_W3_BT_ACT = 7;
const char HAL_UART2_TXD_PIN_M_UART2_TXD = 8;
const char HAL_UART2_TXD_PIN_M_DMIC1_CLK = 9;
const char HAL_UART2_TXD_PIN_M_AUDIO_EXT_SYNC_EN1 = 10;
const char HAL_UART2_TXD_PIN_M_EINT = 12;
const char HAL_UART2_TXD_PIN_M_DEBUGMON5 = 13;
const char HAL_UART2_TXD_PIN_M_usb_drvvbus = 14;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_UART0_DTE_DCD_PIN = 0xff;
const char HAL_UART0_DTE_DSR_PIN = 0xff;
const char HAL_UART0_DTE_DTR_PIN = 0xff;
const char HAL_UART0_DTE_RI_PIN = 0xff;
const char HAL_UART1_DTE_DCD_PIN = 0xff;
const char HAL_UART1_DTE_DSR_PIN = 0xff;
const char HAL_UART1_DTE_DTR_PIN = 0xff;
const char HAL_UART1_DTE_RI_PIN = 0xff;
const char HAL_UART2_DTE_DCD_PIN = 0xff;
const char HAL_UART2_DTE_DSR_PIN = 0xff;
const char HAL_UART2_DTE_DTR_PIN = 0xff;
const char HAL_UART2_DTE_RI_PIN = 0xff;
const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char BSP_HP_ANA_SW_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char EXT_NTC_POWER_SW_PIN = 0xff;
const char EXT_NTC_ADC_PIN = 0xff;
const char EXT_DSP_POWER_SW_PIN = 0xff;
const char EXT_DSP_CLK_SW_PIN = 0xff;
const char EXT_DSP_RTC_CLK_SW_PIN = 0xff;
const char EXT_DSP_32K_CLK_PIN = 0xff;
const char NOTIFY_EXT_DSP_IRQ_PIN = 0xff;
const char BSP_LED0_PIN = 0xff;
const char BSP_LED1_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_GSENSOR_KEY_PIN = 0xff;
const char BSP_LINE_IN_DET_PIN = 0xff;
const char BSP_LINE_IN_SWITCH_PIN = 0xff;
const char BSP_DETACHABLE_MIC_DET_PIN = 0xff;
const char BSP_IRSENSOR_KEY_PIN = 0xff;
const char BSP_ROTARY_ENCODER0_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER0_PIN_B = 0xff;
const char BSP_ROTARY_ENCODER1_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER1_PIN_B = 0xff;
const char BSP_ROTARY_ENCODER2_PIN_A = 0xff;
const char BSP_ROTARY_ENCODER2_PIN_B = 0xff;
const char BSP_PSENSOR_KEY_EVENT_NOTIFY_PIN = 0xff;
const char BSP_PSENSOR_KEY_POWER_PIN = 0xff;
const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN = 0xff;
const char BSP_DUAL_CHIP_TRIGGER_RESET_PIN = 0xff;
const char BSP_DUAL_CHIP_TRIGGER_POWER_KEY_PIN = 0xff;


const char HAL_I2C_MASTER_0_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_0_SDA_PIN = 0xff;
const char HAL_I2C_MASTER_2_SCL_PIN = 0xff;
const char HAL_I2C_MASTER_2_SDA_PIN = 0xff;
const char HAL_I2C_AO_SCL_PIN = 0xff;
const char HAL_I2C_AO_SDA_PIN = 0xff;
const char HAL_AUXADC_1_PIN = 0xff;
const char HAL_AUXADC_2_PIN = 0xff;
const char HAL_AUXADC_3_PIN = 0xff;
const char HAL_AUXADC_4_PIN = 0xff;
const char HAL_AUXADC_5_PIN = 0xff;
const char HAL_AUXADC_6_PIN = 0xff;
const char HAL_AUXADC_7_PIN = 0xff;
const char HAL_MSDC_0_CK_PIN = 0xff;
const char HAL_MSDC_0_CK1_PIN = 0xff;
const char HAL_MSDC_0_CK2_PIN = 0xff;
const char HAL_MSDC_0_CM_PIN = 0xff;
const char HAL_MSDC_0_DA0_PIN = 0xff;
const char HAL_MSDC_0_DA1_PIN = 0xff;
const char HAL_MSDC_0_DA2_PIN = 0xff;
const char HAL_MSDC_0_DA3_PIN = 0xff;
const char HAL_PWM_0_PIN = 0xff;
const char HAL_PWM_1_PIN = 0xff;
const char HAL_PWM_2_PIN = 0xff;
const char HAL_PWM_3_PIN = 0xff;
const char HAL_PWM_4_PIN = 0xff;
const char HAL_PWM_5_PIN = 0xff;
const char HAL_PWM_6_PIN = 0xff;
const char HAL_PWM_7_PIN = 0xff;
const char HAL_PWM_8_PIN = 0xff;
const char HAL_PWM_9_PIN = 0xff;
const char HAL_UART0_RTS_PIN = 0xff;
const char HAL_UART0_CTS_PIN = 0xff;
const char HAL_UART1_TXD_PIN = 0xff;
const char HAL_UART1_RTS_PIN = 0xff;
const char HAL_UART1_CTS_PIN = 0xff;
const char HAL_SPI_MASTER0_CS0_PIN = 0xff;
const char HAL_SPI_MASTER0_CS1_PIN = 0xff;
const char HAL_SPI_MASTER0_CS2_PIN = 0xff;
const char HAL_SPI_MASTER0_CS3_PIN = 0xff;
const char HAL_SPI_MASTER0_SCK_PIN = 0xff;
const char HAL_SPI_MASTER0_MISO_PIN = 0xff;
const char HAL_SPI_MASTER0_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER0_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER1_CS0_PIN = 0xff;
const char HAL_SPI_MASTER1_CS1_PIN = 0xff;
const char HAL_SPI_MASTER1_CS2_PIN = 0xff;
const char HAL_SPI_MASTER1_CS3_PIN = 0xff;
const char HAL_SPI_MASTER1_SCK_PIN = 0xff;
const char HAL_SPI_MASTER1_MISO_PIN = 0xff;
const char HAL_SPI_MASTER1_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER1_SIO3_PIN = 0xff;
const char HAL_SPI_MASTER2_CS0_PIN = 0xff;
const char HAL_SPI_MASTER2_CS1_PIN = 0xff;
const char HAL_SPI_MASTER2_CS2_PIN = 0xff;
const char HAL_SPI_MASTER2_CS3_PIN = 0xff;
const char HAL_SPI_MASTER2_SCK_PIN = 0xff;
const char HAL_SPI_MASTER2_MISO_PIN = 0xff;
const char HAL_SPI_MASTER2_MOSI_PIN = 0xff;
const char HAL_SPI_MASTER2_SIO2_PIN = 0xff;
const char HAL_SPI_MASTER2_SIO3_PIN = 0xff;
const char HAL_SPI_SLV0_CS_PIN = 0xff;
const char HAL_SPI_SLV0_SCK_PIN = 0xff;
const char HAL_SPI_SLV0_MISO_PIN = 0xff;
const char HAL_SPI_SLV0_MOSI_PIN = 0xff;
const char HAL_SPI_SLV0_SIO2_PIN = 0xff;
const char HAL_SPI_SLV0_SIO3_PIN = 0xff;
const char HAL_I2S_MST0_CK_PIN = 0xff;
const char HAL_I2S_MST0_MCLK_PIN = 0xff;
const char HAL_I2S_MST0_RX_PIN = 0xff;
const char HAL_I2S_MST0_TX_PIN = 0xff;
const char HAL_I2S_MST0_WS_PIN = 0xff;
const char HAL_I2S_MST2_CK_PIN = 0xff;
const char HAL_I2S_MST2_MCLK_PIN = 0xff;
const char HAL_I2S_MST2_RX_PIN = 0xff;
const char HAL_I2S_MST2_TX_PIN = 0xff;
const char HAL_I2S_MST2_WS_PIN = 0xff;
const char HAL_I2S_MST3_CK_PIN = 0xff;
const char HAL_I2S_MST3_MCLK_PIN = 0xff;
const char HAL_I2S_MST3_RX_PIN = 0xff;
const char HAL_I2S_MST3_TX_PIN = 0xff;
const char HAL_I2S_MST3_WS_PIN = 0xff;
const char HAL_I2S_SLV0_CK_PIN = 0xff;
const char HAL_I2S_SLV0_RX_PIN = 0xff;
const char HAL_I2S_SLV0_TX_PIN = 0xff;
const char HAL_I2S_SLV0_WS_PIN = 0xff;
const char HAL_I2S_SLV1_CK_PIN = 0xff;
const char HAL_I2S_SLV1_RX_PIN = 0xff;
const char HAL_I2S_SLV1_TX_PIN = 0xff;
const char HAL_I2S_SLV1_WS_PIN = 0xff;
const char HAL_I2S_SLV2_CK_PIN = 0xff;
const char HAL_I2S_SLV2_RX_PIN = 0xff;
const char HAL_I2S_SLV2_TX_PIN = 0xff;
const char HAL_I2S_SLV2_WS_PIN = 0xff;
const char HAL_I2S_SLV3_CK_PIN = 0xff;
const char HAL_I2S_SLV3_RX_PIN = 0xff;
const char HAL_I2S_SLV3_TX_PIN = 0xff;
const char HAL_I2S_SLV3_WS_PIN = 0xff;


/*Output for SmartCharger variable names*/
const char HAL_UART0_RXD_PIN_M_UART0_TXD = 0xff;
const char HAL_UART1_TXD_PIN_M_GPIO = 0xff;
const char HAL_UART1_TXD_PIN_M_UART1_TXD = 0xff;





