typedef enum
{
    AUA_BUDSFRAME_READ_SYSTEM_STATUS = 0x01,
    AUA_BUDSFRAME_WRITE_NVKEY = 0x02,
    AUA_BUDSFRAME_READ_NVKEY = 0x03,
    AUA_BUDSFRAME_SEND_RACE_CMD = 0x04,
    AUA_BUDSFRAME_SEND_RACE_CMD_RESP = 0x05,
    AUA_BUDSFRAME_POWER_ON = 0x06,
    AUA_BUDSFRAME_POWER_OFF = 0x07,
    AUA_BUDSFRAME_CPU_RESET = 0x08,
    AUA_BUDSFRAME_FACTORY_RESET = 0x09,
    AUA_BUDSFRAME_WRITE_LOCAL_MAC_ADDR = 0xA,
    AUA_BUDSFRAME_READ_LOCAL_MAC_ADDR = 0xB,
    AUA_BUDSFRAME_PROGRAM_FW_UPDATE = 0xC,
    AUA_BUDSRAME_RACE_NOTI_ON_OFF = 0xD,
    AUA_BUDSFRAME_TEST_DATA = 0xE,

    AUA_BUDSFRAME_HEARTHROUGH_RESPONSE_PACKETISER = 0x80,
    AUA_BUDSFRAME_HEARTHROUGH_NOTIFICATION_PACKETISER = 0x81,
}AUDEARA_BTULL_MESSAGE_FRAMES_T;

bool AudearaGetNotificationState(void);
void Audeara_BT_send_notify_proc(uint8_t * data, uint16_t length);