#!/bin/bash
set -x

mv ./dsp/middleware/MTK ./dsp/middleware/airoha
mv ./dsp/prebuilt/middleware/MTK ./dsp/prebuilt/middleware/airoha
mv ./dsp/tools/mtk ./dsp/tools/airoha
mv ./mcu/config/module/middleware/MTK ./mcu/config/module/middleware/airoha
mv ./mcu/driver/CMSIS/Device/MTK ./mcu/driver/CMSIS/Device/airoha
mv ./mcu/middleware/MTK ./mcu/middleware/airoha
mv ./mcu/middleware/third_party/tfm/platform/ext/target/mtk ./mcu/middleware/third_party/tfm/platform/ext/target/airoha
mv ./mcu/doc/readme/middleware/MTK ./mcu/doc/readme/middleware/airoha
mv ./mcu/prebuilt/middleware/MTK ./mcu/prebuilt/middleware/airoha
mv ./mcu/tools/mtk ./mcu/tools/airoha

echo 	dsp/.rule.mk	 > tmp
echo 	dsp/config/chip/mt2833/chip.mk	 >> tmp
echo 	dsp/config/chip/mt2833/common.mk	 >> tmp
echo 	dsp/doc/dummy/doc/api/api_mt2833_dsp.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/aac_decoder/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/aac_decoder/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/agc/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/agc/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/clk_skew/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/clk_skew/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/clk_skew_protected/Makefile	 >> tmp
echo 	dsp/middleware/airoha/dspalg/clk_skew_protected/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/clk_skew_protected/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/compander/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/compander/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/cvsd_decoder/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/cvsd_decoder/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/ec_nr/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/ec_nr/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/gsensor_processing/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/inc/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/ins/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/ins/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/leakage_compensation/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/leakage_compensation/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/msbc_decoder/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/msbc_decoder/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/peq/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/peq/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/sbc_decoder/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/sbc_decoder/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/src/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/src/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/voice_plc/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/voice_plc/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspalg/wwe/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/wwe/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2822/Makefile	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2822/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2822/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2833/Makefile	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2833/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspfw/anc_protected/port/chip/mt2833/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspfw/port/chip/mt2822/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspfw/port/chip/mt2833/module.mk	 >> tmp
echo 	dsp/middleware/airoha/stream/module.mk	 >> tmp
echo 	dsp/middleware/airoha/stream/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/verno/module.mk	 >> tmp
echo 	dsp/middleware/airoha/verno/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/clk_skew/mt2822/module.mk	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/leakage_compensation/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/wwe/ama/mt2822/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/wwe/gsound/mt2822/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/wwe/inhouse/mt2822/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspfw/anc/mt2822/module.mk	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspfw/anc/mt2822/readme.txt	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspfw/anc/mt2833/module.mk	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspfw/anc/mt2833/readme.txt	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_cell.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_cell_ainr.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_cell_leaudio.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_cell_ull.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_ainr.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_headset.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_leaudio.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_leaudio_src.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_speaker.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_ull_earbuds.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_8m_evb_ull_headset.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_ainr.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_cell_adapt_anc.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_dual_chip_slave.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_leaudio_dongle.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_speaker.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_ull_dongle.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_ull_earbuds.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_65_evb_ull_earbuds_IGO.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_68_evb.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_68_evb_dual_chip_master.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_68_evb_leaudio.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/feature_68_evb_speaker.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/apps/dsp0_headset_ref_design/XT-XCC/test_feature_65_evb_plain.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/test_loads/dsp0_headset_slt/XT-XCC/feature_65_cell.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/test_loads/dsp0_headset_slt/XT-XCC/feature_65_evb.mk	 >> tmp
echo 	dsp/project/ab1565_ab1568_evk/test_loads/dsp0_headset_slt/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2822/apps/dsp0_headset_ref_design/XT-XCC/feature_mt2822x_evb.mk	 >> tmp
echo 	dsp/project/mt2822/apps/dsp0_headset_ref_design/XT-XCC/feature_mt2822x_evb_1mic_inear.mk	 >> tmp
echo 	dsp/project/mt2822/apps/dsp0_headset_ref_design/XT-XCC/feature_mt2822x_evb_2mic_inear.mk	 >> tmp
echo 	dsp/project/mt2822/apps/dsp0_headset_ref_design/XT-XCC/feature_mt2822x_evk.mk	 >> tmp
echo 	dsp/project/mt2822/apps/dsp0_headset_ref_design/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_coremark/XT-XCC/chip.mk	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_headset_slt/XT-XCC/feature_mt2822x_evb.mk	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_headset_slt/XT-XCC/feature_mt2822x_evb_1mic_inear.mk	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_headset_slt/XT-XCC/feature_mt2822x_evb_2mic_inear.mk	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_headset_slt/XT-XCC/feature_mt2822x_evk.mk	 >> tmp
echo 	dsp/project/mt2822/test_loads/dsp0_headset_slt/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2833/apps/dsp0_headset_ref_design/XT-XCC/feature.mk	 >> tmp
echo 	dsp/project/mt2833/apps/dsp0_headset_ref_design/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2833/templates/dsp0_headset_ref_design_backup/XT-XCC/feature.mk	 >> tmp
echo 	dsp/project/mt2833/templates/dsp0_headset_ref_design_backup/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2833_fpga/apps/dsp0_headset_ref_design/XT-XCC/feature.mk	 >> tmp
echo 	dsp/project/mt2833_fpga/apps/dsp0_headset_ref_design/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2833_fpga/templates/dsp0_headset_ref_design_backup/XT-XCC/feature.mk	 >> tmp
echo 	dsp/project/mt2833_fpga/templates/dsp0_headset_ref_design_backup/XT-XCC/Makefile	 >> tmp
echo 	dsp/project/mt2833_fpga/test_load/dsp0_coremark/XT-XCC/chip.mk	 >> tmp
echo 	dsp/readme.txt	 >> tmp
echo 	mcu/.rule.mk	 >> tmp
echo 	mcu/buildTestCase.sh	 >> tmp
echo 	mcu/config/chip/mt2833/chip.mk	 >> tmp
echo 	mcu/config/chip/mt2833/common.mk	 >> tmp
echo 	mcu/config/module/driver/board/mt25x3_hdk/module.mk	 >> tmp
echo 	mcu/config/module/middleware/MTK/audio/module.mk	 >> tmp
echo 	mcu/config/module/middleware/MTK/battery_management/module.mk	 >> tmp
echo 	mcu/doc/dummy/doc_btaudio_addon/api_addon/addon_bt_audio.txt	 >> tmp
echo 	mcu/doc/dummy/doc_common/api/api_mt2833.txt	 >> tmp
echo 	mcu/driver/board/mt2833x_evb/ept/module.mk	 >> tmp
echo 	mcu/driver/board/mt2833x_evk/ept/module.mk	 >> tmp
echo 	mcu/driver/board/mt2833x_fpga/ept/module.mk	 >> tmp
echo 	mcu/driver/chip/inc/hal_nvic.h	 >> tmp
echo 	mcu/driver/chip/mt2833/inc/hal_crypt_internal.h	 >> tmp
echo 	mcu/driver/chip/mt2833/src/GCC/module.mk	 >> tmp
echo 	mcu/driver/chip/mt2833/src_core/GCC/module.mk	 >> tmp
echo 	mcu/driver/chip/mt2833/src_protected/GCC/module.mk	 >> tmp
echo 	mcu/kernel/service/Makefile	 >> tmp
echo 	mcu/kernel/service/module.mk	 >> tmp
echo 	mcu/kernel/service/mux/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ama/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ama/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ama_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/ama_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ama_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/atci/at_command/at_command_audio.c	 >> tmp
echo 	mcu/middleware/airoha/atci/inc/atci_doxygen.h	 >> tmp
echo 	mcu/middleware/airoha/atci/module.mk	 >> tmp
echo 	mcu/middleware/airoha/atci/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/anc_control/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/anc_control_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/audio/anc_control_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio/anc_control_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/anc_monitor/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/audio_mixer/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/audio_transmitter/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio/audio_transmitter/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/bt_codec/inc/bt_hfp_codec_internal.h	 >> tmp
echo 	mcu/middleware/airoha/audio/bt_codec/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/codec_manager/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/inc/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/leakage_detection/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/linein_playback/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio/mp3_codec/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/port/mt2822/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio/port/mt2833/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio/prompt_control/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/record_control/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/sbc_codec/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/src/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/usb_audio_playback/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/usb_audio_record/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/user_trigger_adaptive_ff/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio/wav_codec/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio_fft/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio_fft/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/audio_manager/module.mk	 >> tmp
echo 	mcu/middleware/airoha/audio_manager/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/avm_direct_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/avm_direct_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/avm_direct_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/battery_management/module.mk	 >> tmp
echo 	mcu/middleware/airoha/battery_management/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ble_ancs/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ble_ancs/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ble_ancs_protected/EWARM/libbleancs_IAR.ewp	 >> tmp
echo 	mcu/middleware/airoha/ble_ancs_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/ble_ancs_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ble_bas/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ble_bas/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ble_dis/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ble_dis/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/ble_ias/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ble_ias/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bluetooth/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bluetooth/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bluetooth_service/bt_device_manager_module.mk	 >> tmp
echo 	mcu/middleware/airoha/bluetooth_service/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bluetooth_service/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_air/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_air/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_aws_mce_report/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_aws_mce_report/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_callback_manager/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_callback_manager/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_connection_manager/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_connection_manager/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_fast_pair/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_fast_pair/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/bt_fast_pair_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/bt_fast_pair_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_role_handover/module.mk	 >> tmp
echo 	mcu/middleware/airoha/bt_role_handover/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/fota/module.mk	 >> tmp
echo 	mcu/middleware/airoha/fota/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/2523/type_def.h	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/2811/type_def.h	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/2822/type_def.h	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/2833/type_def.h	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_2523/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_2523/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_2811/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_2822/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_7687/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_7698/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/driver/rtos/driverlib_third_party/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/build_lib.sh	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/driverlib_7687/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/driverlib_7698/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/hblib_ble/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/hblib_ble/multi_adv/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project/rtos/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/a2dp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/airupdate_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/avrcp_lib/avrcp_br_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/avrcp_lib/avrcp_eh_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/avrcp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/aws_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/aws_mce_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/build_lib.sh	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/ctp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_155x/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_155x/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_156x/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_156x/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2523/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2523/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2811/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2811/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2822/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2822/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2833/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_2833/module.mk	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/driverlib_7698/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/goep_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/hblib_ble/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/hfp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/hid_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/hsp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/mapc_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/pbapc_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/project_duo/rtos/spp_lib/Makefile	 >> tmp
echo 	mcu/middleware/airoha/hummingbird/src/inc/bt_hci_spec.h	 >> tmp
echo 	mcu/middleware/airoha/iap2/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/iap2/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/iap2_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/iap2_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/iap2_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/key/common/inc/airo_key_event.h	 >> tmp
echo 	mcu/middleware/airoha/key/module.mk	 >> tmp
echo 	mcu/middleware/airoha/key/psensor_key/inc/airo_key_psensor.h	 >> tmp
echo 	mcu/middleware/airoha/key/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/mfi_coprocessor/module.mk	 >> tmp
echo 	mcu/middleware/airoha/mfi_coprocessor/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/mfi_coprocessor_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/mfi_coprocessor_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/mfi_coprocessor_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/module_log/module.mk	 >> tmp
echo 	mcu/middleware/airoha/module_log/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/nvdm/module.mk	 >> tmp
echo 	mcu/middleware/airoha/nvdm/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/nvdm_core/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/nvdm_core/src_core/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/nvdm_core/src_core/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/pikachu/btcon/Makefile	 >> tmp
echo 	mcu/middleware/airoha/pikachu/btcon/module.mk	 >> tmp
echo 	mcu/middleware/airoha/pikachu/btcon/moduleGenLib.mk	 >> tmp
echo 	mcu/middleware/airoha/pikachu/btcon/moduleSource.mk	 >> tmp
echo 	mcu/middleware/airoha/port_service/module.mk	 >> tmp
echo 	mcu/middleware/airoha/port_service/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/race_cmd/module.mk	 >> tmp
echo 	mcu/middleware/airoha/race_cmd/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/rofs/module.mk	 >> tmp
echo 	mcu/middleware/airoha/rofs/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/secure_boot_private_protected/Makefile	 >> tmp
echo 	mcu/middleware/airoha/secure_boot_private_protected/module.mk	 >> tmp
echo 	mcu/middleware/airoha/serial_nand/inc/NAND_FDM.h	 >> tmp
echo 	mcu/middleware/airoha/serial_nand/module.mk	 >> tmp
echo 	mcu/middleware/airoha/serial_nand/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/serial_nand_protected/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/serial_nand_protected/src_protected/EWARM/cm4/serial_nand.ewp	 >> tmp
echo 	mcu/middleware/airoha/serial_nand_protected/src_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/serial_nand_protected/src_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/serial_nor/module.mk	 >> tmp
echo 	mcu/middleware/airoha/serial_nor/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/sink/module.mk	 >> tmp
echo 	mcu/middleware/airoha/sink/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/smart_charger/module.mk	 >> tmp
echo 	mcu/middleware/airoha/smart_charger/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/testframework/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ui_shell/module.mk	 >> tmp
echo 	mcu/middleware/airoha/ui_shell/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/usb/module.mk	 >> tmp
echo 	mcu/middleware/airoha/usb/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/usb/src/_common/usb.c	 >> tmp
echo 	mcu/middleware/airoha/usb/src/msc/usbms_state.c	 >> tmp
echo 	mcu/middleware/airoha/va_model_manager/module.mk	 >> tmp
echo 	mcu/middleware/airoha/va_model_manager/readme.txt	 >> tmp
echo 	mcu/middleware/airoha/va_model_manager_protected/GCC/Makefile	 >> tmp
echo 	mcu/middleware/airoha/va_model_manager_protected/GCC/module.mk	 >> tmp
echo 	mcu/middleware/airoha/verno/module.mk	 >> tmp
echo 	mcu/middleware/airoha/verno/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/ama/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/ama_iap2/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/audio/anc/module.mk	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/audio/anc/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/audio/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/ble_ancs/module.mk	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/ble_ancs/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/iap2/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/mfi_coprocessor/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/nvdm/module.mk	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/nvdm/readme.txt	 >> tmp
echo 	mcu/prebuilt/middleware/airoha/serial_nand/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/bootloader/GCC/feature_secure_boot.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/bootloader/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_dongle.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_dongle_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_dongle_leaudio_teams.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_evb.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_65_evk_leaudio_dongle.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/feature_option_switch.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/GCC/test_feature_65_evk_plain.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/dongle_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell_v3.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell_v3_ainr.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_cell_v3_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_ainr.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_emp_share_1wire.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_leaudio_1wire.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_ull_xiaowei.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_8m_evk_xiaoai.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_cell_v2.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evb.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evb_1wire.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_1wire.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_emp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_emp_share.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_share.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_ull_va.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_65_evk_xiaoai_xiaowei.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_earbuds.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_earbuds_emp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_earbuds_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evb.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evb_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evb_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evk_1wire.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_68_evk_ull_a2dp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/feature_secure_boot.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/GCC/test_feature_65_evk_plain.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/src/apps/app_smart_charger/app_smcharger_utils.c	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/earbuds_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_8m_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_8m_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_dual_evk_slave.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_dual_proto1_slave.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_evb.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_evb_emp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_65_evk_emp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_dual_evk_master.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_dual_proto1_master.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evb_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk_emp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk_leaudio_nolinein.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_evk_ull_a2dp.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_headset.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/feature_68_headset_ull.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/GCC/test_feature_68_evk_plain.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/src/apps/app_smart_charger/app_smcharger_utils.c	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/headset_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/iot_testframework/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/GCC/feature_65_8m_evk_leaudio_src.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/GCC/feature_65_evk_leaudio_src.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/src/apps/app_smart_charger/app_smcharger_utils.c	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_bsa_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_65_8m_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_65_8m_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_65_8m_evk_leaudio_src.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_68_earbuds_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_68_evb_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/feature_68_evk_leaudio.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/GCC/test_feature_65_evk_plain.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/src/apps/app_smart_charger/app_smcharger_utils.c	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_pts/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/GCC/feature_65_8m_evk_leaudio_src.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/GCC/feature_65_evk_leaudio_src.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/src/apps/app_smart_charger/app_smcharger_utils.c	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/leaudio_source_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/GCC/feature_65_8m_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/GCC/feature_65_evb.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/GCC/feature_65_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/GCC/feature_68_evk.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/apps/speaker_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/templates/freertos_create_thread/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/templates/no_rtos_initialize_system/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/1565_evb_sd_test/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/DVT/peripheral/dvt_esc/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/esc_flash_hqa/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/esc_support_multi_flash_type/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/fatfs_test/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/flash_mvg_104/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/flash_stress_104/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/hqa_rtc/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/nvdm_refine_assert/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/rotary_encoder_test/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/spi_master_to_slave/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/spi_slave_from_master/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/spi_test/GCC/Makefile	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/spi_test/src/test/desense_module.mk	 >> tmp
echo 	mcu/project/ab1565_ab1568_evk/test_loads/spi_test/src/test/module.mk	 >> tmp
echo 	mcu/project/common/test_cases/buildCases	 >> tmp
echo 	mcu/project/common/test_cases/hb_ble/gap/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_ble/gatt/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_ble/sleep/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/a2dp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/avrcp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/gap/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/hfp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/hsp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/pbapc/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/hb_duo/spp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/inet/httpd/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/Makefile	 >> tmp
echo 	mcu/project/common/test_cases/MTBF/bt/gap/bt_gap_001/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/MTBF/bt/gap/bt_gap_002/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/MTBF/bt/gap/bt_gap_005/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/MTBF/bt/spp/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/MTBF/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/sensor_subsys/sensor_mtbf/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/sensor_subsys/sensor_sanity_test/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/sensor_subsys/sensor_test/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/sink/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/test_framework/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/test_framework/test_framework_000/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/test_framework/test_framework_001/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/test_framework/test_framework_007/MakeConfig	 >> tmp
echo 	mcu/project/common/test_cases/test_framework/test_framework_008/MakeConfig	 >> tmp
echo 	mcu/project/mt2833/apps/bootloader/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/apps/earbuds_ref_design/GCC/feature_mt2833s_evb.mk	 >> tmp
echo 	mcu/project/mt2833/apps/earbuds_ref_design/GCC/feature_mt2833s_evk.mk	 >> tmp
echo 	mcu/project/mt2833/apps/earbuds_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/apps/earbuds_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833/apps/headset_ref_design/GCC/feature_mt2833s_evb.mk	 >> tmp
echo 	mcu/project/mt2833/apps/headset_ref_design/GCC/feature_mt2833s_evk.mk	 >> tmp
echo 	mcu/project/mt2833/apps/headset_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/apps/headset_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/mt2833/apps/headset_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833/templates/freertos_create_thread/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/templates/no_rtos_initialize_system/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/test_loads/sleep_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/test_loads/smt/GCC/feature_mt2833s_evb.mk	 >> tmp
echo 	mcu/project/mt2833/test_loads/smt/GCC/feature_mt2833s_evk.mk	 >> tmp
echo 	mcu/project/mt2833/test_loads/smt/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833/test_loads/smt/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/mt2833/test_loads/smt/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/bootloader/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/earbuds_ref_design/GCC/feature_mt2833_fpga.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/earbuds_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/earbuds_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/earbuds_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/headset_ref_design/GCC/feature_mt2833_fpga.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/headset_ref_design/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/headset_ref_design/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/mt2833_fpga/apps/headset_ref_design/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/earbuds_ref_design_backup/GCC/feature_mt2833_fpga.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/earbuds_ref_design_backup/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/earbuds_ref_design_backup/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/freertos_create_thread/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/headset_ref_design_backup/GCC/feature_mt2833_fpga.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/headset_ref_design_backup/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/headset_ref_design_backup/inc/nvdm_config_factory_reset.h	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/headset_ref_design_backup/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/templates/no_rtos_initialize_system/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_it_testcase/hal_gpio_testcase/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_it_testcase/hal_spi_it_testcase/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_it_testcase/hal_uart_it_testcase/uart_testcase_sleep_mode/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_ut_testcase/hal_gpio_testcase/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_ut_testcase/hal_spim_ut_testcase/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_cases/hal_ut_testcase/hal_spis_ut_testcase/MakeConfig	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Battery_management/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/dsp_idram_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioADDA.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioANCTestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioGainTestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioI2STestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioI2STestItem_Piter.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioMemIFTestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioPCMTestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioPMIC.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioPmicTestItem.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/audiosys/src/AudioSLTTestCase.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/audio/audio_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/BT/avm_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/BT/bt_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/aes/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/aesotf/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/aesotf_esc_sram/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/cache/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/ccni/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/ccni/src/cm_sfc_test_main.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/dma/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/dma_s/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/dvt_adc/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/dvt_i2c_master/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/dvt_trng/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/eint_dvt/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/eint_dvt/src/test/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/esc_flash/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/esc_sram/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/fatfs/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/gpio_eint_nvic_ns/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/gpio_eint_nvic_s/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/ivp/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/msdc/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/nvic/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/sfc/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/sfc/src/cm_sfc_test_main.c	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/smph/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/spi/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/uart/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/DVT/peripheral/wdt/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/esc_psram_memory_performance_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/esc_stt_mvg/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/flash_mvg_104Mhz/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/flash_stress_104Mhz/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/fpga_basic_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_coremark/GCC/chip.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_coremark/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_i2c/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_i2c/GCC/Makefile~	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_msdc/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_ntc_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/hqa_rtc/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Imax_load/GCC/feature_mt2822a_evb.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Imax_load/GCC/feature_mt2822s_evb.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Imax_load/GCC/feature_mt2822s_evk.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Imax_load/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/Imax_load/src/apps/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/limit_trustzone/freertos_create_thread/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/limit_trustzone/no_rtos_initialize_system/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/limit_trustzone/secure_no_rtos_demo/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/logging_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/memory_stress_test/GCC/chip.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/memory_stress_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/psram_esc_demo/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/sleep_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/sleep_test_for_ost/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/smt/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/spi_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/spi_test/src/test/desense_module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/spi_test/src/test/module.mk	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/sw_dma_test/GCC/Makefile	 >> tmp
echo 	mcu/project/mt2833_fpga/test_loads/usb/GCC/Makefile	 >> tmp
echo 	mcu/readme.txt	 >> tmp
echo 	dsp/middleware/airoha/dspfw/port/chip/ab156x/module.mk	 >> tmp
echo 	dsp/middleware/airoha/dspalg/audio_loopback_test/module.mk	 >> tmp
echo 	dsp/prebuilt/middleware/airoha/dspalg/clk_skew/ab156x/module.mk	 >> tmp



cat tmp |xargs sed -i 's/MTK\\/airoha\\/g'
cat tmp |xargs sed -i 's/MTK\//airoha\//g'
cat tmp |xargs sed -i 's/MTK\s/airoha /g'

rm -f tmp

mv ./dsp/kernel/service/heapsize_guard/inc/mtk_HeapSizeGuard.h ./dsp/kernel/service/heapsize_guard/inc/airoha_HeapSizeGuard.h
mv ./dsp/kernel/service/heapsize_guard/src/mtk_HeapSizeGuard.c ./dsp/kernel/service/heapsize_guard/src/airoha_HeapSizeGuard.c
mv ./mcu/kernel/service/inc/mtk_HeapSizeGuard.h ./mcu/kernel/service/inc/airoha_HeapSizeGuard.h
mv ./mcu/kernel/service/src/mtk_HeapSizeGuard.c ./mcu/kernel/service/src/airoha_HeapSizeGuard.c
mv ./mcu/tools/airoha/MTK/Coverage/mtk_covinfo_hw.o ./mcu/tools/airoha/airoha/Coverage/airoha_covinfo_hw.o
mv ./mcu/tools/airoha/MTK/Coverage/mtk_covinfo_sw.o ./mcu/tools/airoha/airoha/Coverage/airoha_covinfo_sw.o

sed -i 's/mtk_HeapSizeGuard.c/airoha_HeapSizeGuard.c/g' dsp/kernel/service/heapsize_guard/module.mk
sed -i 's/mtk_HeapSizeGuard.c/airoha_HeapSizeGuard.c/g' mcu/kernel/service/module.mk

echo "mcu/tools/scripts/build/copy_firmware.sh" |xargs sed -i 's/MTK\\/airoha\\/g'
echo "mcu/tools/scripts/build/copy_firmware.sh" |xargs sed -i 's/MTK\//airoha\//g'
echo "mcu/tools/scripts/build/copy_firmware.sh" |xargs sed -i 's/MTK\s/airoha /g'

