/*
 * Generated by Airoha Easy PinMux Tool Version 2.8.0 for AB1588. Copyright Airoha Inc. (C) 2015.
 * 2022-03-08 16:40:01:0204
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
