/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef __HID_KEYCODE_TABLE_HH_
#define __HID_KEYCODE_TABLE_HH_

//#define ATTACHED_OFFSET  (REPORT_ID_KEYBOARD << 12)
#define ATTACHED_OFFSET  0x00

//#define ATTACHED_OFFSET_CONSUMER (REPORT_ID_KEYBOARD_CONSUMER << 12)
#define ATTACHED_OFFSET_CONSUMER 0x00


#define    KC_NO                       (0x00 | ATTACHED_OFFSET)
#define    KC_ROLL_OVER                (0x01 | ATTACHED_OFFSET)
#define    KC_POST_FAIL                (0x02 | ATTACHED_OFFSET)
#define    KC_UNDEFINED                (0x03 | ATTACHED_OFFSET)
#define    KC_A                        (0x04 | ATTACHED_OFFSET)
#define    KC_B                        (0x05 | ATTACHED_OFFSET)
#define    KC_C                        (0x06 | ATTACHED_OFFSET)
#define    KC_D                        (0x07 | ATTACHED_OFFSET)
#define    KC_E                        (0x08 | ATTACHED_OFFSET)
#define    KC_F                        (0x09 | ATTACHED_OFFSET)
#define    KC_G                        (0x0A | ATTACHED_OFFSET)
#define    KC_H                        (0x0B | ATTACHED_OFFSET)
#define    KC_I                        (0x0C | ATTACHED_OFFSET)
#define    KC_J                        (0x0D | ATTACHED_OFFSET)
#define    KC_K                        (0x0E | ATTACHED_OFFSET)
#define    KC_L                        (0x0F | ATTACHED_OFFSET)
#define    KC_M                        (0x10 | ATTACHED_OFFSET)
#define    KC_N                        (0x11 | ATTACHED_OFFSET)
#define    KC_O                        (0x12 | ATTACHED_OFFSET)
#define    KC_P                        (0x13 | ATTACHED_OFFSET)
#define    KC_Q                        (0x14 | ATTACHED_OFFSET)
#define    KC_R                        (0x15 | ATTACHED_OFFSET)
#define    KC_S                        (0x16 | ATTACHED_OFFSET)
#define    KC_T                        (0x17 | ATTACHED_OFFSET)
#define    KC_U                        (0x18 | ATTACHED_OFFSET)
#define    KC_V                        (0x19 | ATTACHED_OFFSET)
#define    KC_W                        (0x1A | ATTACHED_OFFSET)
#define    KC_X                        (0x1B | ATTACHED_OFFSET)
#define    KC_Y                        (0x1C | ATTACHED_OFFSET)
#define    KC_Z                        (0x1D | ATTACHED_OFFSET)
#define    KC_1                        (0x1E | ATTACHED_OFFSET)
#define    KC_2                        (0x1F | ATTACHED_OFFSET)
#define    KC_3                        (0x20 | ATTACHED_OFFSET)
#define    KC_4                        (0x21 | ATTACHED_OFFSET)
#define    KC_5                        (0x22 | ATTACHED_OFFSET)
#define    KC_6                        (0x23 | ATTACHED_OFFSET)
#define    KC_7                        (0x24 | ATTACHED_OFFSET)
#define    KC_8                        (0x25 | ATTACHED_OFFSET)
#define    KC_9                        (0x26 | ATTACHED_OFFSET)
#define    KC_0                        (0x27 | ATTACHED_OFFSET)

#define    KC_ENTER                    (0x28 | ATTACHED_OFFSET)
#define    KC_ESCAPE                   (0x29 | ATTACHED_OFFSET)
#define    KC_BSPACE                   (0x2A | ATTACHED_OFFSET)
#define    KC_TAB                      (0x2B | ATTACHED_OFFSET)
#define    KC_SPACE                    (0x2C | ATTACHED_OFFSET)
#define    KC_MINUS                    (0x2D | ATTACHED_OFFSET)
#define    KC_EQUAL                    (0x2E | ATTACHED_OFFSET)
#define    KC_LBRACKET                 (0x2F | ATTACHED_OFFSET)
#define    KC_RBRACKET                 (0x30 | ATTACHED_OFFSET)
#define    KC_BSLASH                   (0x31 | ATTACHED_OFFSET)
#define    KC_NONUS_HASH               (0x32 | ATTACHED_OFFSET)
#define    KC_SCOLON                   (0x33 | ATTACHED_OFFSET)
#define    KC_QUOTE                    (0x34 | ATTACHED_OFFSET)
#define    KC_GRAVE                    (0x35 | ATTACHED_OFFSET)
#define    KC_COMMA                    (0x36 | ATTACHED_OFFSET)
#define    KC_DOT                      (0x37 | ATTACHED_OFFSET)
#define    KC_SLASH                    (0x38 | ATTACHED_OFFSET)
#define    KC_CAPSLOCK                 (0x39 | ATTACHED_OFFSET)
#define    KC_F1                       (0x3A | ATTACHED_OFFSET)
#define    KC_F2                       (0x3B | ATTACHED_OFFSET)
#define    KC_F3                       (0x3C | ATTACHED_OFFSET)
#define    KC_F4                       (0x3D | ATTACHED_OFFSET)
#define    KC_F5                       (0x3E | ATTACHED_OFFSET)
#define    KC_F6                       (0x3F | ATTACHED_OFFSET)
#define    KC_F7                       (0x40 | ATTACHED_OFFSET)
#define    KC_F8                       (0x41 | ATTACHED_OFFSET)
#define    KC_F9                       (0x42 | ATTACHED_OFFSET)
#define    KC_F10                      (0x43 | ATTACHED_OFFSET)
#define    KC_F11                      (0x44 | ATTACHED_OFFSET)
#define    KC_F12                      (0x45 | ATTACHED_OFFSET)
#define    KC_PSCREEN                  (0x46 | ATTACHED_OFFSET)
#define    KC_SCROLLLOCK               (0x47 | ATTACHED_OFFSET)
#define    KC_PAUSE                    (0x48 | ATTACHED_OFFSET)
#define    KC_INSERT                   (0x49 | ATTACHED_OFFSET)
#define    KC_HOME                     (0x4A | ATTACHED_OFFSET)
#define    KC_PGUP                     (0x4B | ATTACHED_OFFSET)
#define    KC_DELETE                   (0x4C | ATTACHED_OFFSET)
#define    KC_END                      (0x4D | ATTACHED_OFFSET)
#define    KC_PGDOWN                   (0x4E | ATTACHED_OFFSET)
#define    KC_RIGHT                    (0x4F | ATTACHED_OFFSET)

#define    KC_LEFT                     (0x50 | ATTACHED_OFFSET)
#define    KC_DOWN                     (0x51 | ATTACHED_OFFSET)
#define    KC_UP                       (0x52 | ATTACHED_OFFSET)
#define    KC_NUMLOCK                  (0x53 | ATTACHED_OFFSET)
#define    KC_KP_SLASH                 (0x54 | ATTACHED_OFFSET)
#define    KC_KP_ASTERISK              (0x55 | ATTACHED_OFFSET)
#define    KC_KP_MINUS                 (0x56 | ATTACHED_OFFSET)
#define    KC_KP_PLUS                  (0x57 | ATTACHED_OFFSET)
#define    KC_KP_ENTER                 (0x58 | ATTACHED_OFFSET)
#define    KC_KP_1                     (0x59 | ATTACHED_OFFSET)
#define    KC_KP_2                     (0x5A | ATTACHED_OFFSET)
#define    KC_KP_3                     (0x5B | ATTACHED_OFFSET)
#define    KC_KP_4                     (0x5C | ATTACHED_OFFSET)
#define    KC_KP_5                     (0x5D | ATTACHED_OFFSET)
#define    KC_KP_6                     (0x5E | ATTACHED_OFFSET)
#define    KC_KP_7                     (0x5F | ATTACHED_OFFSET)
#define    KC_KP_8                     (0x60 | ATTACHED_OFFSET)
#define    KC_KP_9                     (0x61 | ATTACHED_OFFSET)
#define    KC_KP_COMPOSE               (0x65 | ATTACHED_OFFSET)

#define    KC_LCTRL                    (0xE0 | ATTACHED_OFFSET)
#define    KC_LSHIFT                   (0xE1 | ATTACHED_OFFSET)
#define    KC_LALT                     (0xE2 | ATTACHED_OFFSET)
#define    KC_LGUI                     (0xE3 | ATTACHED_OFFSET)
#define    KC_RCTRL                    (0xE4 | ATTACHED_OFFSET)
#define    KC_RSHIFT                   (0xE5 | ATTACHED_OFFSET)
#define    KC_RALT                     (0xE6 | ATTACHED_OFFSET)
#define    KC_RGUI                     (0xE7 | ATTACHED_OFFSET)







#define        KC2_UNASSIGNED                                                           (0x0000 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CONSUMER_CONTROL_CA                                                  (0x0001 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_NUMERIC_KEY_PAD_NARY                                                 (0x0002 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PROGRAMMABLE_BUTTONS_NARY                                            (0x0003 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MICROPHONE_CA                                                        (0x0004 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_HEADPHONE_CA                                                         (0x0005 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_GRAPHIC_EQUALIZER_CA                                                 (0x0006 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_10_OSC                                                               (0x0020 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_100_OSC                                                              (0x0021 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AM_PM_OSC                                                            (0x0022 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_POWER_OOC                                                            (0x0030 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_RESET_OSC                                                            (0x0031 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SLEEP_OSC                                                            (0x0032 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SLEEP_AFTER_OSC                                                      (0x0033 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SLEEP_MODE_RTC                                                       (0x0034 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ILLUMINATION_OOC                                                     (0x0035 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FUNCTION_BUTTONS_NARY                                                (0x0036 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_OOC                                                             (0x0040 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_PICK_OSC                                                        (0x0041 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_UP_OSC                                                          (0x0042 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_DOWN_OSC                                                        (0x0043 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_LEFT_OSC                                                        (0x0044 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_RIGHT_OSC                                                       (0x0045 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_ESCAPE_OSC                                                      (0x0046 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_VALUE_INCREASE_OSC                                              (0x0047 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MENU_VALUE_DECREASE_OSC                                              (0x0048 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_DATA_ON_SCREEN_OOC                                                   (0x0060 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CLOSED_CAPTION_OOC                                                   (0x0061 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CLOSED_CAPTION_SELECT_OSC                                            (0x0062 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_VCR_OR_TV_OOC                                                        (0x0063 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BROADCAST_MODE_OSC                                                   (0x0064 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SNAPSHOT_OSC                                                         (0x0065 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_STILL_OSC                                                            (0x0066 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SELECTION_NARY                                                       (0x0080 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ASSIGN_SELECTION_OSC                                                 (0x0081 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MODE_STEP_OSC                                                        (0x0082 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_RECALL_LAST_OSC                                                      (0x0083 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ENTER_CHANNEL_OSC                                                    (0x0084 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ORDER_MOVIE_OSC                                                      (0x0085 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_LC                                                           (0x0086 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECTION_NARY                                                 (0x0087 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_COMPUTER_SEL                                            (0x0088 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_TV_SEL                                                  (0x0089 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_WWW_SEL                                                 (0x008A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_DVD_SEL                                                 (0x008B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_TELEPHONE_SEL                                           (0x008C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_PROGRAM_GUIDE_SEL                                       (0x008D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_VIDEO_PHONE_SEL                                         (0x008E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_GAMES_SEL                                               (0x008F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_MESSAGES_SEL                                            (0x0090 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_CD_SEL                                                  (0x0091 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_VCR_SEL                                                 (0x0092 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_TUNER_SEL                                               (0x0093 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_QUIT_OSC                                                             (0x0094 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_HELP_OOC                                                             (0x0095 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_TAPE_SEL                                                (0x0096 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_CABLE_SEL                                               (0x0097 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_SATELLITE_SEL                                           (0x0098 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_SECURITY_SEL                                            (0x0099 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_HOME_SEL                                                (0x009A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_CALL_SEL                                                (0x009B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_INCREMENT_OSC                                                (0x009C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_DECREMENT_OSC                                                (0x009D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDIA_SELECT_SAP_SEL                                                 (0x009E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_VCR_PLUS_OSC                                                         (0x00A0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ONCE_OSC                                                             (0x00A1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_DAILY_OSC                                                            (0x00A2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_WEEKLY_OSC                                                           (0x00A3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MONTHLY_OSC                                                          (0x00A4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PLAY_OOC                                                             (0x00B0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PAUSE_OOC                                                            (0x00B1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_RECORD_OOC                                                           (0x00B2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FAST_FORWARD_OOC                                                     (0x00B3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_REWIND_OOC                                                           (0x00B4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SCAN_NEXT_TRACK_OSC                                                  (0x00B5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SCAN_PREVIOUS_TRACK_OSC                                              (0x00B6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_STOP_OSC                                                             (0x00B7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_EJECT_OSC                                                            (0x00B8 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_RANDOM_PLAY_OOC                                                      (0x00B9 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SELECT_DISC_NARY                                                     (0x00BA | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ENTER_DISC_MC                                                        (0x00BB | ATTACHED_OFFSET_CONSUMER)
#define        KC2_REPEAT_OSC                                                           (0x00BC | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TRACKING_LC                                                          (0x00BD | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TRACK_NORMAL_OSC                                                     (0x00BE | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SLOW_TRACKING_LC                                                     (0x00BF | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FRAME_FORWARD_RTC                                                    (0x00C0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FRAME_BACK_RTC                                                       (0x00C1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MARK_OSC                                                             (0x00C2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CLEAR_MARK_OSC                                                       (0x00C3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_REPEAT_FROM_MARK_OOC                                                 (0x00C4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_RETURN_TO_MARK_OSC                                                   (0x00C5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SEARCH_MARK_FORWARD_OSC                                              (0x00C6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SEARCH_MARK_BACKWARDS_OSC                                            (0x00C7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_COUNTER_RESET_OSC                                                    (0x00C8 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SHOW_COUNTER_OSC                                                     (0x00C9 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TRACKING_INCREMENT_RTC                                               (0x00CA | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TRACKING_DECREMENT_RTC                                               (0x00CB | ATTACHED_OFFSET_CONSUMER)
#define        KC2_STOP_OR_EJECT_OSC                                                    (0x00CC | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PLAY_OR_PAUSE_OSC                                                    (0x00CD | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PLAY_OR_SKIP_OSC                                                     (0x00CE | ATTACHED_OFFSET_CONSUMER)
#define        KC2_VOLUME_LC                                                            (0x00E0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BALANCE_LC                                                           (0x00E1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MUTE_OOC                                                             (0x00E2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BASS_LC                                                              (0x00E3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TREBLE_LC                                                            (0x00E4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BASS_BOOST_OOC                                                       (0x00E5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SURROUND_MODE_OSC                                                    (0x00E6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_LOUDNESS_OOC                                                         (0x00E7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MPX_OOC                                                              (0x00E8 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_VOLUME_INCREMENT_RTC                                                 (0x00E9 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_VOLUME_DECREMENT_RTC                                                 (0x00EA | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SPEED_SELECT_OSC                                                     (0x00F0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PLAYBACK_SPEED_NARY                                                  (0x00F1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_STANDARD_PLAY_SEL                                                    (0x00F2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_LONG_PLAY_SEL                                                        (0x00F3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_EXTENDED_PLAY_SEL                                                    (0x00F4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SLOW_OSC                                                             (0x00F5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FAN_ENABLE_OOC                                                       (0x0100 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FAN_SPEED_LC                                                         (0x0101 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_LIGHT_ENABLE_OOC                                                     (0x0102 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_LIGHT_ILLUMINATION_LEVEL_LC                                          (0x0103 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CLIMATE_CONTROL_ENABLE_OOC                                           (0x0104 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ROOM_TEMPERATURE_LC                                                  (0x0105 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SECURITY_ENABLE_OOC                                                  (0x0106 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_FIRE_ALARM_OSC                                                       (0x0107 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_POLICE_ALARM_OSC                                                     (0x0108 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_PROXIMITY_LC                                                         (0x0109 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MOTION_OSC                                                           (0x010A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_DURESS_ALARM_OSC                                                     (0x010B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_HOLDUP_ALARM_OSC                                                     (0x010C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_MEDICAL_ALARM_OSC                                                    (0x010D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BALANCE_RIGHT_RTC                                                    (0x0150 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BALANCE_LEFT_RTC                                                     (0x0151 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BASS_INCREMENT_RTC                                                   (0x0152 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_BASS_DECREMENT_RTC                                                   (0x0153 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TREBLE_INCREMENT_RTC                                                 (0x0154 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_TREBLE_DECREMENT_RTC                                                 (0x0155 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SPEAKER_SYSTEM_CL                                                    (0x0160 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_LEFT_CL                                                      (0x0161 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_RIGHT_CL                                                     (0x0162 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_CENTER_CL                                                    (0x0163 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_FRONT_CL                                                     (0x0164 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_CENTER_FRONT_CL                                              (0x0165 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_SIDE_CL                                                      (0x0166 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_SURROUND_CL                                                  (0x0167 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_LOW_FREQUENCY                                                (0x0168 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_TOP_CL                                                       (0x0169 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_CHANNEL_UNKNOWN_CL                                                   (0x016A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SUB_CHANNEL_LC                                                       (0x0170 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SUB_CHANNEL_INCREMENT_OSC                                            (0x0171 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_SUB_CHANNEL_DECREMENT_OSC                                            (0x0172 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ALTERNATE_AUDIO_INCREMENT_OSC                                        (0x0173 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_ALTERNATE_AUDIO_DECREMENT_OSC                                        (0x0174 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_APPLICATION_LAUNCH_BUTTONS_NARY                                      (0x0180 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LAUNCH_BUTTON_CONFIGURATION                                       (0x0181 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_PROGRAMMABLE_BUTTON                                               (0x0182 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CONSUMER_CONTROL                                                  (0x0183 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_WORD_PROCESSOR_SEL                                                (0x0184 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_TEXT_EDITOR_SEL                                                   (0x0185 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_SPREADSHEET_SEL                                                   (0x0186 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_GRAPHICS_EDITOR_SEL                                               (0x0187 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_PRESENTATION_APP_SEL                                              (0x0188 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DATABASE_APP_SEL                                                  (0x0189 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_EMAIL_READER_SEL                                                  (0x018A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_NEWSREADER_SEL                                                    (0x018B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_VOICEMAIL_SEL                                                     (0x018C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CONTACTS_OR_ADDRESS_BOOK_SEL                                      (0x018D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CALENDAR_OR_SCHEDULE_SEL                                          (0x018E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_TASK_OR_PROJECT_MANAGER_SEL                                       (0x018F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LOG_OR_JOURNAL_OR_TIMECARD_SEL                                    (0x0190 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CHECKBOOK_OR_FINANCE_SEL                                          (0x0191 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CALCULATOR_SEL                                                    (0x0192 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_AV_CAPTURE_OR_PLAYBACK_SEL                                        (0x0193 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LOCAL_MACHINE_BROWSER_SEL                                         (0x0194 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LAN_OR_WAN_BROWSER_SEL                                            (0x0195 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_INTERNET_BROWSER_SEL                                              (0x0196 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_REMOTE_NETWORKING_OR_ISP                                          (0x0197 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_NETWORK_CONFERENCE_SEL                                            (0x0198 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_NETWORK_CHAT_SEL                                                  (0x0199 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_TELEPHONY_OR_DIALER_SEL                                           (0x019A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LOGON_SEL                                                         (0x019B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LOGOFF_SEL                                                        (0x019C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_LOGON_OR_LOGOFF_SEL                                               (0x019D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_TERMINAL_LOCK_OR_SCREENSAVER_SEL                                  (0x019E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CONTROL_PANEL_SEL                                                 (0x019F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_COMMAND_LINE_PROCESSOR_OR_RUN_SEL                                 (0x01A0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_PROCESS_OR_TASK_MANAGER_SEL                                       (0x01A1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_SELECT_TASK_OR_APPLICATION_SEL                                    (0x01A2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_NEXT_TASK_OR_APPLICATION_SEL                                      (0x01A3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_PREVIOUS_TASK_OR_APPLICATION_SEL                                  (0x01A4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_PREEMPTIVE_HALT                                                   (0x01A5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_INTEGRATED_HELP_CENTER_SEL                                        (0x01A6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DOCUMENTS_SEL                                                     (0x01A7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_THESAURUS_SEL                                                     (0x01A8 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DICTIONARY_SEL                                                    (0x01A9 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DESKTOP_SEL                                                       (0x01AA | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_SPELL_CHECK_SEL                                                   (0x01AB | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_GRAMMAR_CHECK_SEL                                                 (0x01AC | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_WIRELESS_STATUS_SEL                                               (0x01AD | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_KEYBOARD_LAYOUT_SEL                                               (0x01AE | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_VIRUS_PROTECTION_SEL                                              (0x01AF | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ENCRYPTION_SEL                                                    (0x01B0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_SCREEN_SAVER_SEL                                                  (0x01B1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ALARMS_SEL                                                        (0x01B2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CLOCK_SEL                                                         (0x01B3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_FILE_BROWSER_SEL                                                  (0x01B4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_POWER_STATUS_SEL                                                  (0x01B5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_IMAGE_BROWSER_SEL                                                 (0x01B6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_AUDIO_BROWSER_SEL                                                 (0x01B7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_MOVIE_BROWSER_SEL                                                 (0x01B8 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DIGITAL_RIGHTS_MANAGER_SEL                                        (0x01B9 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_DIGITAL_WALLET_SEL                                                (0x01BA | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_INSTANT_MESSAGING_SEL                                             (0x01BC | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_OEM_FEATURES_OR__TIPS_OR_TUTORIAL                                 (0x01BD | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_OEM_HELP_SEL                                                      (0x01BE | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ONLINE_COMMUNITY_SEL                                              (0x01BF | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ENTERTAINMENT_CONTENT                                             (0x01C0 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ONLINE_SHOPPING_BROWSER_SEL                                       (0x01C1 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_SMARTCARD_INFORMATION_OR_HELP_SEL                                 (0x01C2 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_MARKET_MONITOR_OR_FINANCE                                         (0x01C3 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_CUSTOMIZED_CORPORATE_NEWS                                         (0x01C4 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_ONLINE_ACTIVITY_BROWSER_SEL                                       (0x01C5 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_RESEARCH_OR_SEARCH_BROWSER_SEL                                    (0x01C6 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AL_AUDIO_PLAYER_SEL                                                  (0x01C7 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_GENERIC_GUI_APPLICATION                                              (0x0200 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NEW_SEL                                                           (0x0201 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_OPEN_SEL                                                          (0x0202 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_CLOSE_SEL                                                         (0x0203 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_EXIT_SEL                                                          (0x0204 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_MAXIMIZE_SEL                                                      (0x0205 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_MINIMIZE_SEL                                                      (0x0206 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SAVE_SEL                                                          (0x0207 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PRINT_SEL                                                         (0x0208 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PROPERTIES_SEL                                                    (0x0209 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_UNDO_SEL                                                          (0x021A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_COPY_SEL                                                          (0x021B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_CUT_SEL                                                           (0x021C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PASTE_SEL                                                         (0x021D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_ALL_SEL                                                    (0x021E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FIND_SEL                                                          (0x021F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FIND_AND_REPLACE_SEL                                              (0x0220 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SEARCH_SEL                                                        (0x0221 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_GO_TO_SEL                                                         (0x0222 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_HOME_SEL                                                          (0x0223 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_BACK_SEL                                                          (0x0224 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FORWARD_SEL                                                       (0x0225 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_STOP_SEL                                                          (0x0226 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_REFRESH_SEL                                                       (0x0227 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PREVIOUS_LINK_SEL                                                 (0x0228 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NEXT_LINK_SEL                                                     (0x0229 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_BOOKMARKS_SEL                                                     (0x022A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_HISTORY_SEL                                                       (0x022B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SUBSCRIPTIONS_SEL                                                 (0x022C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ZOOM_IN_SEL                                                       (0x022D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ZOOM_OUT_SEL                                                      (0x022E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ZOOM_LC                                                           (0x022F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FULL_SCREEN_VIEW_SEL                                              (0x0230 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NORMAL_VIEW_SEL                                                   (0x0231 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_VIEW_TOGGLE_SEL                                                   (0x0232 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SCROLL_UP_SEL                                                     (0x0233 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SCROLL_DOWN_SEL                                                   (0x0234 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SCROLL_LC                                                         (0x0235 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PAN_LEFT_SEL                                                      (0x0236 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PAN_RIGHT_SEL                                                     (0x0237 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PAN_LC                                                            (0x0238 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NEW_WINDOW_SEL                                                    (0x0239 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_TILE_HORIZONTALLY_SEL                                             (0x023A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_TILE_VERTICALLY_SEL                                               (0x023B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FORMAT_SEL                                                        (0x023C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_EDIT_SEL                                                          (0x023D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_BOLD_SEL                                                          (0x023E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ITALICS_SEL                                                       (0x023F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_UNDERLINE_SEL                                                     (0x0240 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_STRIKETHROUGH_SEL                                                 (0x0241 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SUBSCRIPT_SEL                                                     (0x0242 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SUPERSCRIPT_SEL                                                   (0x0243 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ALL_CAPS_SEL                                                      (0x0244 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ROTATE_SEL                                                        (0x0245 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_RESIZE_SEL                                                        (0x0246 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FLIP_HORIZONTAL_SEL                                               (0x0247 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FLIP_VERTICAL_SEL                                                 (0x0248 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_MIRROR_HORIZONTAL_SEL                                             (0x0249 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_MIRROR_VERTICAL_SEL                                               (0x024A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FONT_SELECT_SEL                                                   (0x024B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FONT_COLOR_SEL                                                    (0x024C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FONT_SIZE_SEL                                                     (0x024D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_LEFT_SEL                                                  (0x024E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_CENTER_H_SEL                                              (0x024F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_RIGHT_SEL                                                 (0x0250 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_BLOCK_H_SEL                                               (0x0251 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_TOP_SEL                                                   (0x0252 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_CENTER_V_SEL                                              (0x0253 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_BOTTOM_SEL                                                (0x0254 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_JUSTIFY_BLOCK_V_SEL                                               (0x0255 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INDENT_DECREASE_SEL                                               (0x0256 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INDENT_INCREASE_SEL                                               (0x0257 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NUMBERED_LIST_SEL                                                 (0x0258 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_RESTART_NUMBERING_SEL                                             (0x0259 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_BULLETED_LIST_SEL                                                 (0x025A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PROMOTE_SEL                                                       (0x025B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DEMOTE_SEL                                                        (0x025C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_YES_SEL                                                           (0x025D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_NO_SEL                                                            (0x025E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_CANCEL_SEL                                                        (0x025F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_CATALOG_SEL                                                       (0x0260 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_BUY_OR_CHECKOUT_SEL                                               (0x0261 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ADD_TO_CART_SEL                                                   (0x0262 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_EXPAND_SEL                                                        (0x0263 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_EXPAND_ALL_SEL                                                    (0x0264 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_COLLAPSE_SEL                                                      (0x0265 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_COLLAPSE_ALL_SEL                                                  (0x0266 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PRINT_PREVIEW_SEL                                                 (0x0267 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PASTE_SPECIAL_SEL                                                 (0x0268 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_MODE_SEL                                                   (0x0269 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DELETE_SEL                                                        (0x026A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_LOCK_SEL                                                          (0x026B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_UNLOCK_SEL                                                        (0x026C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_PROTECT_SEL                                                       (0x026D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_UNPROTECT_SEL                                                     (0x026E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ATTACH_COMMENT_SEL                                                (0x026F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DELETE_COMMENT_SEL                                                (0x0270 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_VIEW_COMMENT_SEL                                                  (0x0271 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_WORD_SEL                                                   (0x0272 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_SENTENCE_SEL                                               (0x0273 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_PARAGRAPH_SEL                                              (0x0274 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_COLUMN_SEL                                                 (0x0275 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_ROW_SEL                                                    (0x0276 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_TABLE_SEL                                                  (0x0277 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_OBJECT_SEL                                                 (0x0278 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_REDO_OR_REPEAT_SEL                                                (0x0279 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SORT_SEL                                                          (0x027A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SORT_ASCENDING_SEL                                                (0x027B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SORT_DESCENDING_SEL                                               (0x027C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FILTER_SEL                                                        (0x027D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SET_CLOCK_SEL                                                     (0x027E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_VIEW_CLOCK_SEL                                                    (0x027F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SELECT_TIME_ZONE_SEL                                              (0x0280 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_EDIT_TIME_ZONES_SEL                                               (0x0281 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SET_ALARM_SEL                                                     (0x0282 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_CLEAR_ALARM_SEL                                                   (0x0283 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SNOOZE_ALARM_SEL                                                  (0x0284 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_RESET_ALARM_SEL                                                   (0x0285 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SYNCHRONIZE_SEL                                                   (0x0286 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SEND_OR_RECEIVE_SEL                                               (0x0287 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SEND_TO_SEL                                                       (0x0288 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_REPLY_SEL                                                         (0x0289 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_REPLY_ALL_SEL                                                     (0x028A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_FORWARD_MSG_SEL                                                   (0x028B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SEND_SEL                                                          (0x028C | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_ATTACH_FILE_SEL                                                   (0x028D | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_UPLOAD_SEL                                                        (0x028E | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DOWNLOAD_SEL                                                      (0x028F | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SET_BORDERS_SEL                                                   (0x0290 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_ROW_SEL                                                    (0x0291 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_COLUMN_SEL                                                 (0x0292 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_FILE_SEL                                                   (0x0293 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_PICTURE_SEL                                                (0x0294 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_OBJECT_SEL                                                 (0x0295 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_INSERT_SYMBOL_SEL                                                 (0x0296 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SAVE_AND_CLOSE_SEL                                                (0x0297 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_RENAME_SEL                                                        (0x0298 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_MERGE_SEL                                                         (0x0299 | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_SPLIT_SEL                                                         (0x029A | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DISRIBUTE_HORIZONTALLY_SEL                                        (0x029B | ATTACHED_OFFSET_CONSUMER)
#define        KC2_AC_DISTRIBUTE_VERTICALLY_SEL                                         (0x029C | ATTACHED_OFFSET_CONSUMER)


#endif // __APP_KEY_MATRIX_DECLARATION__HH_
