/**
wayne.xiong add for factory air test cmd
20200528

**/


#ifndef RACE_CMD_FACTORY_TEST_H
#define RACE_CMD_FACTORY_TEST_H

#include "race_cmd_feature.h"
#ifdef RACE_BT_CMD_ENABLE
#include "stdint.h"
#include "bt_type.h"
#include "bt_hfp.h"
#include "race_cmd.h"

#ifdef __cplusplus
extern "C" {
#endif


#define FACTORY_TEST_BLE_CMD_GET_VERSION     0x9000
#define FACTORY_TEST_BLE_CMD_BT_ADDR_SET    0x9001
#define FACTORY_TEST_SET_A2DP_VOLUME     0x9002
#define FACTORY_TEST_BLE_CMD_FACTORY_REST    0x9003
#define FACTORY_TEST_BLE_CMD_CHANNEL_CHECK   0x9004
#define FACTORY_TEST_BLE_CMD_BT_ADDR_READ       0x9005
#define FACTORY_TEST_BLE_CMD_BATTERY_LEVEL_READ       0x9006
#define FACTORY_TEST_BLE_CMD_SHIPPING_MODE 0x9007
//#define FACTORY_TEST_BLE_CMD_DEVICE_COLOR 0x9008
//#define FACTORY_TEST_BLE_CMD_MINI_UI 0x9009
#define FACTORY_TEST_BLE_CMD_PSENSOR_CALIBRATE 0x900A
#define FACTORY_TEST_BLE_CMD_IR_READ         0x900B
#define FACTORY_TEST_BLE_CMD_IR_THRESHOLD_CALIBRATE        0x900C
#define FACTORY_TEST_BLE_CMD_NTC_STATE_READ        0x900D
#define FACTORY_TEST_BLE_CMD_PSENSOR_PUW_SET        0x900E
#define FACTORY_TEST_BLE_CMD_HW_VERSION        0x900F
//#define FACTORY_TEST_BLE_CMD_BAT_HEATHY_PERCENT2TIME_SET 0x9010
//#define FACTORY_TEST_BLE_CMD_BAT_HEATHY_CTR 0x9011
#define FACTORY_TEST_BLE_CMD_SERIAL_NUMBER  0x9012
#define FACTORY_TEST_BLE_CMD_WRITE_SN_SYNC_RESULT  0x9013
#define FACTORY_TEST_BLE_CMD_TOUCH_LIMIT_DISABLE   0x9014
//#define FACTORY_TEST_BLE_CMD_MFI_CHECK   0x9015
#define FACTORY_TEST_BLE_CMD_HALL_CHECK   0x9016
#define FACTORY_TEST_BLE_CMD_ENTER_SHIPPING_MODE   0x9017
#define FACTORY_TEST_BLE_CMD_POWER_OFF   0x9018
#define FACTORY_TEST_BLE_CMD_TOUCH_TEST_CTR   0x9019
#define FACTORY_TEST_BLE_CMD_TOUCH_READ   0x901A
#define FACTORY_TEST_BLE_CMD_PSENSOR_THD_WIRTE   0x901B
#define FACTORY_TEST_BLE_CMD_GFP_TX_POWER_SET 0x901C
#define FACTORY_TEST_BLE_CMD_TRACKING_LOG 0x901D
#define FACTORY_TEST_BLE_CMD_IR_STATUS_CHECKING 0x901E
//#define FACTORY_TEST_BLE_CMD_AB1571D_VERSION      0x9020
#define FACTORY_TEST_BLE_CMD_LEA_DISABLE 0x901F
#define FACTORY_TEST_BLE_CMD_HX300X_PS_DATA_READ 0x9020
#define FACTORY_TEST_BLE_CMD_HX300X_IIC_INT_CHECK 0x9021
#define FACTORY_TEST_BLE_CMD_HX300X_OPEN_AIR 0x9022
#define FACTORY_TEST_BLE_CMD_HX300X_IN_EAR 0x9023
#define FACTORY_TEST_BLE_CMD_HX300X_OUT_EAR 0x9024
#define FACTORY_TEST_BLE_CMD_HX300X_DATA_SAVE 0x9025
#define FACTORY_TEST_BLE_CMD_HX300X_READ_CALI_SETTING 0x9026
#define FACTORY_TEST_BLE_CMD_HX300X_DEBUG_SWITCH 0x9027
#define FACTORY_TEST_BLE_CMD_HX300X_REG_CTR 0x9028
#define FACTORY_TEST_BLE_CMD_HX300X_READ_ALL_REG 0x9029
#define FACTORY_TEST_BLE_CMD_REWIRE_BTNAME 0x902A
#define FACTORY_TEST_BLE_CMD_WRITE_NAME_SYNC_RESULT  0x902B
#define FACTORY_TEST_BLE_CMD_FACTORY_POWEROFF 0x902C
#define FACTORY_TEST_BLE_CMD_FACTORY_POWEROFF_CHECK 0x902D
#define FACTORY_TEST_BLE_CMD_DUT_FORCE_ON    0x910C
#define FACTORY_TEST_BLE_CMD_CLICK_CNT       0x910D
#define FACTORY_TEST_BLE_CMD_ROLE_HANDOVER   0x910F


void *RACE_CmdHandler_FACTORY_TEST(ptr_race_pkt_t pRaceHeaderCmd, uint16_t length, uint8_t channel_id);
//void RACE_FACTORY_TEST_MFI_STATUS_NOTIFY(uint8_t data);

#endif

#endif
