/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.6 for AB1585. Copyright Airoha Inc. (C) 2015.
 * 2022-12-14 20:23:52:0061
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char BSP_EINTKEY0_EINT = 13;
const unsigned char BSP_EINTKEY1_EINT = 14;
const unsigned char BSP_EINTKEY2_EINT = 15;
const unsigned char BSP_EINTKEY3_EINT = 16;
const unsigned char BSP_CTP_EINT = 0xff;
const unsigned char HAL_ACCDET_EINT = 0xff;
const unsigned char HAL_MSDC_EINT = 0xff;
const unsigned char BSP_GNSS_EINT = 0xff;
const unsigned char BSP_WIFI_EINT = 0xff;
const unsigned char MODEM_EXCEPTION_EINT = 0xff;
const unsigned char MODEM_WAKEUP_EINT = 0xff;
const unsigned char HAL_UART0_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART0_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART1_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART1_DTE_DSR_EINT = 0xff;
const unsigned char HAL_UART2_DTE_RI_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DCD_EINT = 0xff;
const unsigned char HAL_UART2_DTE_DSR_EINT = 0xff;
const unsigned char EXT_DSP_TRIGGER_EINT = 0xff;
const unsigned char BSP_EINTKEY4_EINT = 0xff;
const unsigned char BSP_GSENSOR_KEY_EINT = 0xff;
const unsigned char BSP_LINE_IN_EINT = 0xff;
const unsigned char BSP_ROTARY_ENCODER0_PIN_A_EINT = 0xff;
const unsigned char BSP_ROTARY_ENCODER0_PIN_B_EINT = 0xff;
const unsigned char BSP_DUAL_CHIP_WAKEUP_EINT = 0xff;


const unsigned char BSP_EINTKEY0_ACTIVE_LEVEL = 0;
const unsigned char BSP_EINTKEY1_ACTIVE_LEVEL = 0;
const unsigned char BSP_EINTKEY2_ACTIVE_LEVEL = 0;
const unsigned char BSP_EINTKEY3_ACTIVE_LEVEL = 0;
const unsigned char BSP_EINTKEY4_ACTIVE_LEVEL = 0xFF;



