/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.6 for AB1577S. Copyright Airoha Inc. (C) 2015.
 * 2022-12-15 09:33:30:0661
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef _EPT_GPIO_DRV_H
#define _EPT_GPIO_DRV_H

#define MODE_0  0
#define MODE_1  1
#define MODE_2  2
#define MODE_3  3
#define MODE_4  4
#define MODE_5  5
#define MODE_6  6
#define MODE_7  7
#define MODE_8  8
#define MODE_9  9
#define MODE_10  10
#define MODE_11  11
#define MODE_12  12
#define MODE_13  13
#define MODE_14  14
#define MODE_NC  0

#define PULL_ENABLE  1
#define PULL_DISABLE  0
#define DIR_INPUT  0
#define DIR_OUTPUT  1
#define GPIO_PORTNULL_MODE  0
#define GPIO_PORTNULL_DIR   0
#define GPIO_PORTNULL_OUTPUT_LEVEL  0
#define GPIO_PORTNULL_PU        0
#define GPIO_PORTNULL_PD        0
#define GPIO_PORTNULL_DOUT  0
#define GPIO_PORT0_MODE   MODE_3 // 3:UART0_TXD : Used for UART0_TXD
#define GPIO_PORT1_MODE   MODE_3 // 3:UART0_RXD : Used for UART0_RXD
#define GPIO_PORT2_MODE   MODE_12 // 12:EINT2 : Used for EINT2
#define GPIO_PORT3_MODE   MODE_12 // 12:EINT3 : Used for EINT3
#define GPIO_PORT4_MODE   MODE_12 // 12:EINT4 : Used for EINT4
#define GPIO_PORT5_MODE   MODE_12 // 12:EINT5 : Used for EINT5
#define GPIO_PORT6_MODE   MODE_7 // 7:AUXADC0 : Used for AUXADC0
#define GPIO_PORT7_MODE   MODE_3 // 3:UART1_RXD : Used for UART1_RXD
#define GPIO_PORT8_MODE   MODE_12 // 12:EINT8 : Used for EINT8
#define GPIO_PORT9_MODE   MODE_NC
#define GPIO_PORT10_MODE   MODE_NC
#define GPIO_PORT11_MODE   MODE_2 // 2:I2S_MST1_WS : Used for I2S_MST1_WS
#define GPIO_PORT12_MODE   MODE_2 // 2:I2S_MST1_RX : Used for I2S_MST1_RX
#define GPIO_PORT13_MODE   MODE_2 // 2:I2S_MST1_MCLK : Used for I2S_MST1_MCLK
#define GPIO_PORT14_MODE   MODE_2 // 2:I2S_MST1_TX : Used for I2S_MST1_TX
#define GPIO_PORT15_MODE   MODE_2 // 2:I2S_MST1_CK : Used for I2S_MST1_CK
#define GPIO_PORT16_MODE   MODE_5 // 5:I2C1_SDA : Used for I2C1_SDA
#define GPIO_PORT17_MODE   MODE_5 // 5:I2C1_SCL : Used for I2C1_SCL
#define GPIO_PORT18_MODE   MODE_NC
#define GPIO_PORT19_MODE   MODE_NC
#define GPIO_PORT20_MODE   MODE_8 // 8:UART2_RXD : Used for UART2_RXD
#define GPIO_PORT21_MODE   MODE_8 // 8:UART2_TXD : Used for UART2_TXD
#define GPIO_PORT22_MODE   MODE_NC
#define GPIO_PORT23_MODE   MODE_NC
#define RTC_GPIO_PORT0_MODE   MODE_2 // 2:CTP0 : Used for CTP0
#define RTC_GPIO_PORT1_MODE   MODE_13 // NC : No User
#define RTC_GPIO_PORT2_MODE   MODE_13 // NC : No User


#define GPIO_PORT0_DIR   DIR_INPUT
#define GPIO_PORT1_DIR   DIR_INPUT
#define GPIO_PORT2_DIR   DIR_INPUT
#define GPIO_PORT3_DIR   DIR_INPUT
#define GPIO_PORT4_DIR   DIR_INPUT
#define GPIO_PORT5_DIR   DIR_INPUT
#define GPIO_PORT6_DIR   DIR_INPUT
#define GPIO_PORT7_DIR   DIR_INPUT
#define GPIO_PORT8_DIR   DIR_INPUT
#define GPIO_PORT9_DIR   DIR_INPUT
#define GPIO_PORT10_DIR   DIR_INPUT
#define GPIO_PORT11_DIR   DIR_INPUT
#define GPIO_PORT12_DIR   DIR_INPUT
#define GPIO_PORT13_DIR   DIR_INPUT
#define GPIO_PORT14_DIR   DIR_INPUT
#define GPIO_PORT15_DIR   DIR_INPUT
#define GPIO_PORT16_DIR   DIR_INPUT
#define GPIO_PORT17_DIR   DIR_INPUT
#define GPIO_PORT18_DIR   DIR_INPUT
#define GPIO_PORT19_DIR   DIR_INPUT
#define GPIO_PORT20_DIR   DIR_INPUT
#define GPIO_PORT21_DIR   DIR_INPUT
#define GPIO_PORT22_DIR   DIR_INPUT
#define GPIO_PORT23_DIR   DIR_INPUT
#define RTC_GPIO_PORT0_DIR   DIR_INPUT
#define RTC_GPIO_PORT1_DIR   DIR_INPUT
#define RTC_GPIO_PORT2_DIR   DIR_INPUT


#define GPIO_PORT0_OUTPUT_LEVEL   0
#define GPIO_PORT1_OUTPUT_LEVEL   0
#define GPIO_PORT2_OUTPUT_LEVEL   0
#define GPIO_PORT3_OUTPUT_LEVEL   0
#define GPIO_PORT4_OUTPUT_LEVEL   0
#define GPIO_PORT5_OUTPUT_LEVEL   0
#define GPIO_PORT6_OUTPUT_LEVEL   0
#define GPIO_PORT7_OUTPUT_LEVEL   0
#define GPIO_PORT8_OUTPUT_LEVEL   0
#define GPIO_PORT9_OUTPUT_LEVEL   0
#define GPIO_PORT10_OUTPUT_LEVEL   0
#define GPIO_PORT11_OUTPUT_LEVEL   0
#define GPIO_PORT12_OUTPUT_LEVEL   0
#define GPIO_PORT13_OUTPUT_LEVEL   0
#define GPIO_PORT14_OUTPUT_LEVEL   0
#define GPIO_PORT15_OUTPUT_LEVEL   0
#define GPIO_PORT16_OUTPUT_LEVEL   0
#define GPIO_PORT17_OUTPUT_LEVEL   0
#define GPIO_PORT18_OUTPUT_LEVEL   0
#define GPIO_PORT19_OUTPUT_LEVEL   0
#define GPIO_PORT20_OUTPUT_LEVEL   0
#define GPIO_PORT21_OUTPUT_LEVEL   0
#define GPIO_PORT22_OUTPUT_LEVEL   0
#define GPIO_PORT23_OUTPUT_LEVEL   0
#define RTC_GPIO_PORT0_OUTPUT_LEVEL   0
#define RTC_GPIO_PORT1_OUTPUT_LEVEL   0
#define RTC_GPIO_PORT2_OUTPUT_LEVEL   0


#define GPIO_PORT0_PU   0
#define GPIO_PORT1_PU   1
#define GPIO_PORT2_PU   1
#define GPIO_PORT3_PU   1
#define GPIO_PORT4_PU   1
#define GPIO_PORT5_PU   1
#define GPIO_PORT6_PU   0
#define GPIO_PORT7_PU   1
#define GPIO_PORT8_PU   1
#define GPIO_PORT9_PU   0
#define GPIO_PORT10_PU   0
#define GPIO_PORT11_PU   0
#define GPIO_PORT12_PU   0
#define GPIO_PORT13_PU   0
#define GPIO_PORT14_PU   0
#define GPIO_PORT15_PU   0
#define GPIO_PORT16_PU   1
#define GPIO_PORT17_PU   1
#define GPIO_PORT18_PU   0
#define GPIO_PORT19_PU   0
#define GPIO_PORT20_PU   1
#define GPIO_PORT21_PU   0
#define GPIO_PORT22_PU   0
#define GPIO_PORT23_PU   0
#define RTC_GPIO_PORT0_PU   0
#define RTC_GPIO_PORT1_PU   0
#define RTC_GPIO_PORT2_PU   0


#define GPIO_PORT0_PD   0
#define GPIO_PORT1_PD   0
#define GPIO_PORT2_PD   0
#define GPIO_PORT3_PD   0
#define GPIO_PORT4_PD   0
#define GPIO_PORT5_PD   0
#define GPIO_PORT6_PD   0
#define GPIO_PORT7_PD   0
#define GPIO_PORT8_PD   0
#define GPIO_PORT9_PD   1
#define GPIO_PORT10_PD   1
#define GPIO_PORT11_PD   0
#define GPIO_PORT12_PD   0
#define GPIO_PORT13_PD   0
#define GPIO_PORT14_PD   0
#define GPIO_PORT15_PD   0
#define GPIO_PORT16_PD   0
#define GPIO_PORT17_PD   0
#define GPIO_PORT18_PD   1
#define GPIO_PORT19_PD   1
#define GPIO_PORT20_PD   0
#define GPIO_PORT21_PD   0
#define GPIO_PORT22_PD   1
#define GPIO_PORT23_PD   1
#define RTC_GPIO_PORT0_PD   0
#define RTC_GPIO_PORT1_PD   1
#define RTC_GPIO_PORT2_PD   1




#define EPT_GPIO_PIN_MASK_1   0x00
#define EPT_GPIO_PIN_MASK_0   0x00ffffff


#define GPIO_VOLTAGE_TYPE_0 0x00000000
#define GPIO_VOLTAGE_TYPE_1 0x00000000
#define GPIO_VOLTAGE_TYPE_2 0x00000000
#define GPIO_VOLTAGE_TYPE_3 0x00000000

#endif /* _EPT_GPIO_DRV_H */
