/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.6 for AB1577S. Copyright Airoha Inc. (C) 2015.
 * 2022-12-15 09:33:30:0670
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
