/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.7 for 1582P. Copyright Airoha Inc. (C) 2015.
 * 2023-01-31 10:14:57:0362
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

extern const unsigned char BSP_CTP_EINT;
extern const unsigned char HAL_ACCDET_EINT;
extern const unsigned char HAL_MSDC_EINT;
extern const unsigned char BSP_GNSS_EINT;
extern const unsigned char BSP_WIFI_EINT;
extern const unsigned char MODEM_EXCEPTION_EINT;
extern const unsigned char MODEM_WAKEUP_EINT;
extern const unsigned char HAL_UART0_DTE_RI_EINT;
extern const unsigned char HAL_UART0_DTE_DCD_EINT;
extern const unsigned char HAL_UART0_DTE_DSR_EINT;
extern const unsigned char HAL_UART1_DTE_RI_EINT;
extern const unsigned char HAL_UART1_DTE_DCD_EINT;
extern const unsigned char HAL_UART1_DTE_DSR_EINT;
extern const unsigned char HAL_UART2_DTE_RI_EINT;
extern const unsigned char HAL_UART2_DTE_DCD_EINT;
extern const unsigned char HAL_UART2_DTE_DSR_EINT;
extern const unsigned char EXT_DSP_TRIGGER_EINT;
extern const unsigned char BSP_EINTKEY0_EINT;
extern const unsigned char BSP_EINTKEY1_EINT;
extern const unsigned char BSP_EINTKEY2_EINT;
extern const unsigned char BSP_EINTKEY3_EINT;
extern const unsigned char BSP_EINTKEY4_EINT;
extern const unsigned char BSP_GSENSOR_KEY_EINT;
extern const unsigned char BSP_LINE_IN_EINT;


extern const unsigned char BSP_EINTKEY0_ACTIVE_LEVEL;
extern const unsigned char BSP_EINTKEY1_ACTIVE_LEVEL;
extern const unsigned char BSP_EINTKEY2_ACTIVE_LEVEL;
extern const unsigned char BSP_EINTKEY3_ACTIVE_LEVEL;
extern const unsigned char BSP_EINTKEY4_ACTIVE_LEVEL;



