/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

/**
 * File: nvdm_config_factory_reset.h
 *
 * Description: This file defines the interface of nvdm_config_factory_reset.c.
 *
 */

#ifndef __NVDM_CONFIG_FACTORY_RST_H__
#define __NVDM_CONFIG_FACTORY_RST_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifdef MTK_NVDM_ENABLE

#define FACTORY_RESET_FLAG      (0x55)    /* Flag write in NVDM to indicate that factory reset is requested, all NVDM items except for those in FACTORY_RST_RESERVED_NVDM_ITEM_LIST will be deleted. */
#define FACTORY_RESET_LINK_KEY  (0x56)    /* Flag write in NVDM to indicate that link key reset is requested, only link related NVkey items will be deleted. */

/*
 * This macro defines table of NVDM items that will be reserved after factory reset. Items not in the table will be deleted.
 * 1. The user should put the NVDM items which need to be reserved after factory reset here with group name and item name.
 * 2. Those reserved NVDM items should be reviewed carefully before put them here.
 * 3. See mcu/middleware/airoha/nvdm/inc/nvkey_id_list.h and mcu/middleware/airoha/nvdm/inc/nvdm_id_list.h for more nvdm item details.
 */
#define FACTORY_RST_CLEAR_NVDM_ITEM_LIST \
{\
\
};

#define FACTORY_RST_CLEAR_NVKEY_ITEM_LIST \
{\
    NVID_BT_HOST_LINKKEY_RECORD_01,\
    NVID_BT_HOST_LINKKEY_RECORD_02,\
    NVID_BT_HOST_LINKKEY_RECORD_03,\
    NVID_BT_HOST_LINKKEY_RECORD_04,\
    NVID_BT_HOST_LINKKEY_RECORD_05,\
    NVID_BT_HOST_LINKKEY_RECORD_06,\
    NVID_BT_HOST_LINKKEY_RECORD_07,\
    NVID_BT_HOST_LINKKEY_RECORD_08,\
    NVID_BT_HOST_LINKKEY_RECORD_09,\
    NVID_BT_HOST_LINKKEY_RECORD_10,\
    NVID_BT_HOST_LINKKEY_RECORD_11,\
    NVID_BT_HOST_LINKKEY_RECORD_12,\
    NVID_BT_HOST_LINKKEY_RECORD_13,\
    NVID_BT_HOST_LINKKEY_RECORD_14,\
    NVID_BT_HOST_LINKKEY_RECORD_15,\
    NVID_BT_HOST_LINKKEY_RECORD_16,\
    NVID_BT_HOST_REMOTE_INFO_01,\
    NVID_BT_HOST_REMOTE_INFO_02,\
    NVID_BT_HOST_REMOTE_INFO_03,\
    NVID_BT_HOST_REMOTE_INFO_04,\
    NVID_BT_HOST_REMOTE_INFO_05,\
    NVID_BT_HOST_REMOTE_INFO_06,\
    NVID_BT_HOST_REMOTE_INFO_07,\
    NVID_BT_HOST_REMOTE_INFO_08,\
    NVID_BT_HOST_REMOTE_INFO_09,\
    NVID_BT_HOST_REMOTE_INFO_10,\
    NVID_BT_HOST_REMOTE_INFO_11,\
    NVID_BT_HOST_REMOTE_INFO_12,\
    NVID_BT_HOST_REMOTE_INFO_13,\
    NVID_BT_HOST_REMOTE_INFO_14,\
    NVID_BT_HOST_REMOTE_INFO_15,\
    NVID_BT_HOST_REMOTE_INFO_16,\
    NVID_BT_HOST_REMOTE_INFO_17,\
    NVID_BT_HOST_REMOTE_INFO_18,\
    NVID_BT_HOST_REMOTE_INFO_19,\
    NVID_BT_HOST_REMOTE_INFO_20,\
    NVID_BT_HOST_REMOTE_INFO_21,\
    NVID_BT_HOST_REMOTE_INFO_22,\
    NVID_BT_HOST_REMOTE_INFO_23,\
    NVID_BT_HOST_REMOTE_INFO_24,\
    NVID_BT_HOST_REMOTE_INFO_25,\
    NVID_BT_HOST_REMOTE_INFO_26,\
    NVID_BT_HOST_REMOTE_INFO_27,\
    NVID_BT_HOST_REMOTE_INFO_28,\
    NVID_BT_HOST_REMOTE_INFO_29,\
    NVID_BT_HOST_REMOTE_INFO_MAX,\
    NVID_BT_HOST_REMOTE_SEQUENCE,\
    NVID_BT_HOST_LE_BOND_INFO_1,\
    NVID_BT_HOST_LE_BOND_INFO_2,\
    NVID_BT_HOST_LE_BOND_INFO_3,\
    NVID_BT_HOST_LE_BOND_INFO_4,\
    NVID_BT_HOST_LE_BOND_INFO_5,\
    NVID_BT_HOST_LE_BOND_INFO_6,\
    NVID_BT_HOST_LE_BOND_INFO_7,\
    NVID_BT_HOST_LE_BOND_INFO_8,\
    NVID_BT_HOST_LE_BOND_INFO_9,\
    NVID_BT_HOST_LE_BOND_INFO_10,\
    NVID_BT_HOST_LE_BOND_INFO_11,\
    NVID_BT_HOST_LE_BOND_INFO_12,\
    NVID_BT_HOST_LE_BOND_INFO_13,\
    NVID_BT_HOST_LE_BOND_INFO_14,\
    NVID_BT_HOST_LE_BOND_INFO_15,\
    NVID_BT_HOST_LE_BOND_INFO_16,\
    NVID_BT_HOST_LE_BOND_INFO_17,\
    NVID_BT_HOST_LE_BOND_INFO_18,\
    NVID_BT_HOST_LE_BOND_INFO_19,\
    NVID_BT_HOST_LE_BOND_INFO_20,\
    NVID_BT_HOST_LE_BOND_INFO_ORDER,\
    NVID_BT_HOST_DM_GATT_CACHE_01,\
    NVID_BT_HOST_DM_GATT_CACHE_02,\
    NVID_BT_HOST_DM_GATT_CACHE_03,\
    NVID_BT_HOST_DM_GATT_CACHE_04,\
    NVID_BT_HOST_DM_GATT_CACHE_SEQUENCE,\
    NVID_BT_HOST_HOGP_1,\
    NVID_BT_HOST_HOGP_2,\
    NVID_BT_HOST_HOGP_3,\
    NVID_BT_HOST_HOGP_4,\
    NVID_BT_HOST_HOGP_5,\
    NVID_BT_HOST_HOGP_6,\
    NVID_BT_HOST_HOGP_7,\
    NVID_BT_HOST_HOGP_8,\
    NVID_BT_HOST_HOGP_9,\
    NVID_BT_HOST_HOGP_10,\
    NVID_BT_HOST_RELAY_ENABLE,\
    NVID_BT_HOST_DUT_ENABLE,\
    NVID_BT_HOST_ULL_AUDIO_QUALITY,\
    NVID_BT_LEA_TEST_MODE,\
    NVID_BT_LEA_BONDED_LIST,\
    NVID_BT_LEA_ACTIVE_GROUP,\
    NVID_BT_LEA_SIRK_LIST,\
    NVID_BT_LEA_BCST_QOS_PARAMS,\
    NVID_BT_LEA_VCS_VOLUME_USR,\
    NVID_BT_LEA_VOCS_DATA_USR,\
    NVID_BT_LEA_AICS_GAIN_SET_PROP_USR,\
    NVID_BT_LEA_AICS_GAIN_SETTING_USR,\
    NVID_BT_LEA_SINK_LOCATION_USR,\
    NVID_BT_LEA_SOURCE_LOCATION_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_1_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_2_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_3_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_4_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_5_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_6_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_7_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_8_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_9_USR,\
    NVID_BT_LEA_DESCRIPTION_STR_10_USR,\
    NVID_BT_LEA_ENABLE,\
    NVID_BT_LEA_ENABLE_USR,\
    NVID_FOTA_VERSION,\
    NVID_DSP_ALG_AEQ_DETECT_MISC,\
    NVID_DSP_ALG_PEQ_COF_29,\
    NVID_DSP_ALG_PEQ_COF_30,\
    NVID_DSP_ALG_PEQ_COF_31,\
    NVID_DSP_ALG_PEQ_COF_32,\
    NVID_PERI_LOG_MODULE_SETTING,\
    NVID_APP_DEVICE_NAME_USER,\
    NVID_APP_ENABLE_MP_TEST_MODE,\
    NVID_APP_CUSTOMER_KEY_CFG,\
    NVID_APP_SYSTEM_MODE_SETTING,\
    NVID_APP_AMA_DRIVER_VARIATION,\
    NVID_APP_SELECTED_VA_TYPE,\
    NVID_APP_XIAOWEI_PROPER_VALUE,\
    NVID_APP_XIAOAI_MI_PHONE_ADDR,\
    NVID_APP_PEER_CUSTOMER_KEY_CFG,\
    NVID_APP_XIAOAI_ADDR_MAPPING,\
    NVID_APP_HEAR_THROUGH_USER_CONFIGURATION, \
    NVID_APP_HEARING_AID_USER_CONFIGURATION, \
    NVID_APP_BT_RECONNECT_INFO,\
    NVID_APP_LE_AUDIO_CONN_FLAG,\
    NVID_APP_IN_EAR_MUSIC_ABILITY,\
    NVID_APP_RACE_TOUCH_KEY_ENABLE,\
    NVID_APP_POWER_SAVING_CFG,\
    NVID_APP_IN_EAR_HFP_ABILITY,\
    NVID_APP_ULL_CONFIG,\
    NVID_APP_MULTI_POINT_ENABLE,\
    NVID_APP_CASE_BATTERY_INFO,\
    NVID_APP_FPS_SPOT_EIK,\
    NVID_APP_FPS_SPOT_EID_COUNTER,\
    NVID_APP_ANC_GAIN_CONTROL,\
    NVID_APP_USB_LOGGING_MODE,\
    NVID_APP_USB_CALIBRATION_MODE,\
    NVID_APP_XBOX_VOL_INFO ,\
    NVID_APP_ADVANCE_PT,\
    NVID_APP_LEA_DHSS_PAIR_LE_ADDR,\
    NVID_APP_FPS_SPOT_LAST_EID,\
    NVID_APP_SELF_FITTING_CONFIG,\
    NVID_APP_GSOUND_INIT_STATE,\
    NVID_APP_LINE_IN_AUDIO_PATH,\
    NVID_APP_SIDETONE_VALUE,\
    NVID_APP_FPS_SPOT_UNTRACKING_MODE,\
    NVID_APP_FAST_PAIR_ACCOUNT_KEY,\
    NVID_APP_FAST_PAIR_PERSONALIZED_NAME,\
    NVID_APP_FAST_PAIR_CONNECTED_DEVICES,\
    NVID_APP_FAST_PAIR_IN_USED_ACCOUNT_KEY_ID,\
    NVID_APP_LE_LOCAL_IRK,\
    NVID_APP_LE_RANDOM_ADDRESS,\
    NVID_APP_WM_FATFS_FILE_NUM,\
    NVID_APP_WM_MERGE_SPLIT_MODE,\
    NVID_APP_DONGLE_USB_MODE,\
    NVID_APP_SILENCE_DETECTION,\
    NVID_APP_CALL_RX_EQ_TYPE,\
    NVID_APP_LEA_BIS_VOLUME,\
    NVID_APP_ULL2_SAMPLE_RATE,\
    NVID_APP_BT_SOURCE_DEVICE_INFO,\
    NVID_APP_XIAOAI_KEY_VIDPID,\
    NVID_APP_XIAOAI_SLIENCE_OTA,\
    NVID_APP_XIAOAI_KEY_BROADCAST_COUNT,\
    NVID_APP_XIAOAI_SAVE_CONFIG,\
    NVID_APP_XIAOAI_FAST_CONNECT,\
    NVID_APP_LEA_FEATURE_STATE,\
};

/**
* @brief      This function is to check which reset flag is set and do NVDM re-organization.
*/
void factory_rst_reserved_nvdm_item_list_check(void);


#endif

#ifdef __cplusplus
}
#endif

#endif /* __NVDM_CONFIG_FACTRST_H__ */
