

/**
  * @file    app_customer_common_activity.h
  *
  * @author  wayne.xiong
  *
  * @date    2022/5/27
  *
  * @brief   data process for customer common handle
**/


#ifndef __APP_CUSTOMER_COMMON_ACTIVITY_H__
#define __APP_CUSTOMER_COMMON_ACTIVITY_H__

#include "ui_shell_activity.h"



enum
{
	EVENT_ID_CUSTOMER_COMMON_PROCESS_INPUT = 0,
	EVENT_ID_CUSTOMER_COMMON_CUSTOMER_DATA_REQUEST,
    EVENT_ID_SHIPPING_MODE_STATE_SYNC ,
    EVENT_ID_ECO_CHARGING_STATUS_SYNC,
    EVENT_ID_CUSTOMER_COMMON_CUSTOMER_DATA_SYNC,
    EVENT_ID_UI_SOUNDS_EVENT_SYNC,
    EVENT_ID_ECO_SETTINGS_EVENT_SYNC,
    EVENT_ID_ACTION_BUTTON_CONFIGURATION_EVENT_SYNC,
    EVENT_ID_TOUCH_LOCK_EVENT_SYNC,
    EVENT_ID_APP_VOLUME_API_SYNC,
    EVENT_ID_APP_ANC_SYNC,//10
    EVENT_ID_DEVICE_COLOR_STATE_SYNC,
    EVENT_ID_DEVICE_MINI_UI_STATE_SYNC,
    EVENT_ID_PSENSOR_CALIBRATE_ACTION_SYNC,
    EVENT_ID_CASE_BT_CLEAR_BT_ON,
    EVENT_ID_EQ_SETTINGS_SYNC,
    EVENT_ID_BATTERY_HEATHY_CYCLE_END,
    EVENT_ID_BATTERY_HEATHY_CYCLE_START,
    EVENT_ID_BATTERY_HEATHY_SYNC,
    EVENT_ID_TAKE_OVER_CLEAN,
    EVENT_ID_PROMPT_SYNC,//20
    EVENT_ID_DEVICE_SN_SYNC,
    EVENT_ID_DEVICE_SN_COMPARE,
    EVENT_ID_DEVICE_MFI_CHECK,
    EVENT_ID_DEVICE_HW_VER_SYNC,
    EVENT_ID_ANC_SWITCH,
    EVENT_ID_PROXIMITY_SENSOR_INEAR,
    EVENT_ID_ANC_LEVEL,
    EVENT_ID_TRA_LEVEL,
    EVENT_ID_WEAR_SENSOR_ACTION,
    EVENT_ID_ANC_STATUS_SYNC,//30
    EVENT_ID_APP_PLAY_PAUSE_STATE_SYNC,
    EVENT_ID_ZOUND_NOTIFY_SYNC,
    EVENT_ID_ADIDAS_RUNNING_SYNC,
    EVENT_ID_ZOUND_NOTIFY_CCCD_SYNC,
    EVENT_ID_ZOUND_EQ_SWITCH_SYNC,
    EVENT_ID_ANC_BK_STATUS_SYNC,
    EVENT_ID_LEFT_BATTERY_NOTIFY_CCCD_SYNC,
    EVENT_ID_RIGHT_BATTERY_NOTIFY_CCCD_SYNC,
    EVENT_ID_MAIN_BATTERY_NOTIFY_CCCD_SYNC,
    EVENT_ID_SWITCH_HOLD,//40
    EVENT_ID_DELAY_NOTIFY_BAT,
    EVENT_ID_ANC_KEY_SYNC,
    EVENT_ID_RD_DEBUG,
    EVENT_ID_BLE_BROADCAST_INTERVAL,
    EVENT_ID_DEVICE_LEA_DISABLE_STATE_SYNC,
    EVENT_ID_HX300X_DEBUG_SYNC,
    EVENT_ID_HX300X_READ_ALL_REG,
    EVENT_ID_EASTECH_CALLBACK_PAIR_VP,
    EVENT_ID_EASTECH_PRE_PAIR_VP,
    EVENT_ID_EASTECH_CALLBACK_OCEAN_VP, //50 0x32
    EVENT_ID_EASTECH_VOLUME_VP, //50 0x32
    EVENT_ID_EASTECH_OCEAN_ADJUST_VP, //51 0x33
    EVENT_ID_EASTECH_OCEAN_ADJUST_DOWN_VP, 
    EVENT_ID_EASTECH_OCEAN_IS_PLAY_NOW, 
};

  extern  uint8_t ocean_cnt;
  extern  uint8_t	ocean_vp_vol;  // DEF= VP DEF

typedef struct {

	uint32_t reserved;

} apps_customer_common_local_context_t;

uint16_t app_get_peer_battery_heathy_times(void);


bool apps_customer_common_activity_proc(
      struct _ui_shell_activity *self,
      uint32_t event_group,
      uint32_t event_id,
      void *extra_data,
      size_t data_len);



#endif //__APP_CUSTOMER_COMMON_ACTIVITY_H__





