/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.6 for AB1577S. Copyright Airoha Inc. (C) 2015.
 * 2022-12-15 09:33:30:0667
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

extern const char HAL_UART0_TXD_PIN;
extern const char HAL_UART0_TXD_PIN_M_GPIO;
extern const char HAL_UART0_TXD_PIN_M_SPDIF;
extern const char HAL_UART0_TXD_PIN_M_UART0_TXD;
extern const char HAL_UART0_TXD_PIN_M_PWM0;
extern const char HAL_UART0_TXD_PIN_M_CLKO;
extern const char HAL_UART0_TXD_PIN_M_TEST_P;
extern const char HAL_UART0_TXD_PIN_M_DMIC1_CLK;
extern const char HAL_UART0_TXD_PIN_M_DEBUGMON0;
extern const char HAL_UART0_TXD_PIN_M_usb_line_state0;


extern const char HAL_UART0_RXD_PIN;
extern const char HAL_UART0_RXD_PIN_M_GPIO;
extern const char HAL_UART0_RXD_PIN_M_SPI_MST0_CS0;
extern const char HAL_UART0_RXD_PIN_M_UART0_RXD;
extern const char HAL_UART0_RXD_PIN_M_I2S_SLV0_CK;
extern const char HAL_UART0_RXD_PIN_M_I2C0_SCL;
extern const char HAL_UART0_RXD_PIN_M_DSP_JTMS;
extern const char HAL_UART0_RXD_PIN_M_TEST_N;
extern const char HAL_UART0_RXD_PIN_M_CLKO;
extern const char HAL_UART0_RXD_PIN_M_DMIC1_DAT;
extern const char HAL_UART0_RXD_PIN_M_EINT;
extern const char HAL_UART0_RXD_PIN_M_DEBUGMON1;
extern const char HAL_UART0_RXD_PIN_M_usb_line_state1;


extern const char BSP_EINTKEY0_PIN;
extern const char BSP_EINTKEY0_PIN_M_GPIO;
extern const char BSP_EINTKEY0_PIN_M_SPI_MST0_CS0;
extern const char BSP_EINTKEY0_PIN_M_I2S_MST0_WS;
extern const char BSP_EINTKEY0_PIN_M_UART1_TXD;
extern const char BSP_EINTKEY0_PIN_M_I2S_SLV0_WS;
extern const char BSP_EINTKEY0_PIN_M_I2C0_SDA;
extern const char BSP_EINTKEY0_PIN_M_DSP_JRST;
extern const char BSP_EINTKEY0_PIN_M_TEST_BUS;
extern const char BSP_EINTKEY0_PIN_M_PAD_DFUNC_SFCS0;
extern const char BSP_EINTKEY0_PIN_M_DMIC0_DAT;
extern const char BSP_EINTKEY0_PIN_M_SPDIF;
extern const char BSP_EINTKEY0_PIN_M_PWM0;
extern const char BSP_EINTKEY0_PIN_M_EINT;
extern const char BSP_EINTKEY0_PIN_M_DEBUGMON2;
extern const char BSP_EINTKEY0_PIN_M_usb_data_0;


extern const char BSP_EINTKEY1_PIN;
extern const char BSP_EINTKEY1_PIN_M_GPIO;
extern const char BSP_EINTKEY1_PIN_M_SPI_MST0_MISO;
extern const char BSP_EINTKEY1_PIN_M_I2S_MST0_RX;
extern const char BSP_EINTKEY1_PIN_M_UART1_RXD;
extern const char BSP_EINTKEY1_PIN_M_I2S_SLV0_RX;
extern const char BSP_EINTKEY1_PIN_M_I2C0_SCL;
extern const char BSP_EINTKEY1_PIN_M_AP_JTMS;
extern const char BSP_EINTKEY1_PIN_M_AUXADC3;
extern const char BSP_EINTKEY1_PIN_M_PAD_DFUNC_SOUT;
extern const char BSP_EINTKEY1_PIN_M_DMIC0_CLK;
extern const char BSP_EINTKEY1_PIN_M_DSP_JTMS;
extern const char BSP_EINTKEY1_PIN_M_EINT;
extern const char BSP_EINTKEY1_PIN_M_DEBUGMON3;
extern const char BSP_EINTKEY1_PIN_M_usb_data_1;


extern const char BSP_EINTKEY2_PIN;
extern const char BSP_EINTKEY2_PIN_M_GPIO;
extern const char BSP_EINTKEY2_PIN_M_SPI_MST0_MOSI;
extern const char BSP_EINTKEY2_PIN_M_I2S_MST0_TX;
extern const char BSP_EINTKEY2_PIN_M_SPDIF;
extern const char BSP_EINTKEY2_PIN_M_I2S_SLV0_TX;
extern const char BSP_EINTKEY2_PIN_M_I2C1_SCL;
extern const char BSP_EINTKEY2_PIN_M_DSP_JTDO;
extern const char BSP_EINTKEY2_PIN_M_CTP1_AUXADC2;
extern const char BSP_EINTKEY2_PIN_M_PAD_DFUNC_SIN;
extern const char BSP_EINTKEY2_PIN_M_DMIC1_DAT;
extern const char BSP_EINTKEY2_PIN_M_I2C0_SDA;
extern const char BSP_EINTKEY2_PIN_M_PWM1;
extern const char BSP_EINTKEY2_PIN_M_EINT;
extern const char BSP_EINTKEY2_PIN_M_DEBUGMON4;
extern const char BSP_EINTKEY2_PIN_M_usb_data_2;


extern const char BSP_EINTKEY3_PIN;
extern const char BSP_EINTKEY3_PIN_M_GPIO;
extern const char BSP_EINTKEY3_PIN_M_SPI_MST0_SCK;
extern const char BSP_EINTKEY3_PIN_M_I2S_MST0_CK;
extern const char BSP_EINTKEY3_PIN_M_UART1_RXD;
extern const char BSP_EINTKEY3_PIN_M_I2S_SLV0_CK;
extern const char BSP_EINTKEY3_PIN_M_I2C1_SDA;
extern const char BSP_EINTKEY3_PIN_M_DSP_JTDI;
extern const char BSP_EINTKEY3_PIN_M_CTP2_AUXADC1;
extern const char BSP_EINTKEY3_PIN_M_PAD_DFUNC_SFCK;
extern const char BSP_EINTKEY3_PIN_M_DMIC1_CLK;
extern const char BSP_EINTKEY3_PIN_M_I2C0_SCL;
extern const char BSP_EINTKEY3_PIN_M_PWM2;
extern const char BSP_EINTKEY3_PIN_M_EINT;
extern const char BSP_EINTKEY3_PIN_M_DEBUGMON5;
extern const char BSP_EINTKEY3_PIN_M_usb_data_3;


extern const char HAL_AUXADC_0_PIN;
extern const char HAL_AUXADC_0_PIN_M_GPIO;
extern const char HAL_AUXADC_0_PIN_M_SPI_MST0_MISO;
extern const char HAL_AUXADC_0_PIN_M_I2S_MST0_MCLK;
extern const char HAL_AUXADC_0_PIN_M_UART1_TXD;
extern const char HAL_AUXADC_0_PIN_M_I2S_SLV0_WS;
extern const char HAL_AUXADC_0_PIN_M_I2C0_SDA;
extern const char HAL_AUXADC_0_PIN_M_AP_JTCK;
extern const char HAL_AUXADC_0_PIN_M_AUXADC0;
extern const char HAL_AUXADC_0_PIN_M_UART0_RTS;
extern const char HAL_AUXADC_0_PIN_M_DMIC0_DAT;
extern const char HAL_AUXADC_0_PIN_M_DSP_JTCK;
extern const char HAL_AUXADC_0_PIN_M_EINT;
extern const char HAL_AUXADC_0_PIN_M_DEBUGMON6;
extern const char HAL_AUXADC_0_PIN_M_usb_rx_active;


extern const char HAL_UART1_RXD_PIN;
extern const char HAL_UART1_RXD_PIN_M_GPIO;
extern const char HAL_UART1_RXD_PIN_M_SPI_MST0_CS0;
extern const char HAL_UART1_RXD_PIN_M_I2S_MST0_WS;
extern const char HAL_UART1_RXD_PIN_M_UART1_RXD;
extern const char HAL_UART1_RXD_PIN_M_UART1_TXD;
extern const char HAL_UART1_RXD_PIN_M_I2C1_SDA;
extern const char HAL_UART1_RXD_PIN_M_DSP_JTCK;
extern const char HAL_UART1_RXD_PIN_M_COEX_W1_DAT;
extern const char HAL_UART1_RXD_PIN_M_UART0_CTS;
extern const char HAL_UART1_RXD_PIN_M_DMIC1_CLK;
extern const char HAL_UART1_RXD_PIN_M_BT_EPA_ELNA_ANT_SEL;
extern const char HAL_UART1_RXD_PIN_M_PWM3;
extern const char HAL_UART1_RXD_PIN_M_EINT;
extern const char HAL_UART1_RXD_PIN_M_DEBUGMON7;
extern const char HAL_UART1_RXD_PIN_M_usb_mac_valid;


extern const char BSP_EINTKEY4_PIN;
extern const char BSP_EINTKEY4_PIN_M_GPIO;
extern const char BSP_EINTKEY4_PIN_M_SPI_MST0_MISO;
extern const char BSP_EINTKEY4_PIN_M_I2S_MST0_RX;
extern const char BSP_EINTKEY4_PIN_M_UART0_RTS;
extern const char BSP_EINTKEY4_PIN_M_PWM0;
extern const char BSP_EINTKEY4_PIN_M_I2C1_SCL;
extern const char BSP_EINTKEY4_PIN_M_DSP_JTMS;
extern const char BSP_EINTKEY4_PIN_M_SPDIF;
extern const char BSP_EINTKEY4_PIN_M_AUDIO_EXT_SYNC_EN0;
extern const char BSP_EINTKEY4_PIN_M_DMIC1_DAT;
extern const char BSP_EINTKEY4_PIN_M_BT_EPA_ELNA_CPS;
extern const char BSP_EINTKEY4_PIN_M_PWM4;
extern const char BSP_EINTKEY4_PIN_M_EINT;
extern const char BSP_EINTKEY4_PIN_M_DEBUGMON8;
extern const char BSP_EINTKEY4_PIN_M_usb_phy_clock;


extern const char HAL_I2S_MST1_WS_PIN;
extern const char HAL_I2S_MST1_WS_PIN_M_GPIO;
extern const char HAL_I2S_MST1_WS_PIN_M_SPI_MST0_CS0;
extern const char HAL_I2S_MST1_WS_PIN_M_I2S_MST1_WS;
extern const char HAL_I2S_MST1_WS_PIN_M_UART1_CTS;
extern const char HAL_I2S_MST1_WS_PIN_M_I2S_SLV0_WS;
extern const char HAL_I2S_MST1_WS_PIN_M_CLKO;
extern const char HAL_I2S_MST1_WS_PIN_M_DSP_JRST;
extern const char HAL_I2S_MST1_WS_PIN_M_COEX_W3_BT_PRI;
extern const char HAL_I2S_MST1_WS_PIN_M_DMIC1_CLK;
extern const char HAL_I2S_MST1_WS_PIN_M_BT_EPA_ELNA_CHL;
extern const char HAL_I2S_MST1_WS_PIN_M_PWM5;
extern const char HAL_I2S_MST1_WS_PIN_M_EINT;
extern const char HAL_I2S_MST1_WS_PIN_M_DEBUGMON11;
extern const char HAL_I2S_MST1_WS_PIN_M_usb_opmode0;


extern const char HAL_I2S_MST1_RX_PIN;
extern const char HAL_I2S_MST1_RX_PIN_M_GPIO;
extern const char HAL_I2S_MST1_RX_PIN_M_SPI_MST0_MISO;
extern const char HAL_I2S_MST1_RX_PIN_M_I2S_MST1_RX;
extern const char HAL_I2S_MST1_RX_PIN_M_UART1_RXD;
extern const char HAL_I2S_MST1_RX_PIN_M_I2S_SLV0_RX;
extern const char HAL_I2S_MST1_RX_PIN_M_I2C1_SDA;
extern const char HAL_I2S_MST1_RX_PIN_M_DSP_JTDO;
extern const char HAL_I2S_MST1_RX_PIN_M_CLKO;
extern const char HAL_I2S_MST1_RX_PIN_M_BT_EPA_ELNA_CSD;
extern const char HAL_I2S_MST1_RX_PIN_M_DMIC0_DAT;
extern const char HAL_I2S_MST1_RX_PIN_M_PWM0;
extern const char HAL_I2S_MST1_RX_PIN_M_EINT;
extern const char HAL_I2S_MST1_RX_PIN_M_DEBUGMON12;
extern const char HAL_I2S_MST1_RX_PIN_M_usb_opmode1;


extern const char HAL_I2S_MST1_MCLK_PIN;
extern const char HAL_I2S_MST1_MCLK_PIN_M_GPIO;
extern const char HAL_I2S_MST1_MCLK_PIN_M_SPI_MST0_MOSI;
extern const char HAL_I2S_MST1_MCLK_PIN_M_I2S_MST1_MCLK;
extern const char HAL_I2S_MST1_MCLK_PIN_M_UART1_TXD;
extern const char HAL_I2S_MST1_MCLK_PIN_M_I2S_SLV0_TX;
extern const char HAL_I2S_MST1_MCLK_PIN_M_I2C1_SCL;
extern const char HAL_I2S_MST1_MCLK_PIN_M_UART1_RXD;
extern const char HAL_I2S_MST1_MCLK_PIN_M_GPIO_PIP_SEL_0;
extern const char HAL_I2S_MST1_MCLK_PIN_M_DMIC0_CLK;
extern const char HAL_I2S_MST1_MCLK_PIN_M_AP_JTCK;
extern const char HAL_I2S_MST1_MCLK_PIN_M_EINT;
extern const char HAL_I2S_MST1_MCLK_PIN_M_DEBUGMON13;


extern const char HAL_I2S_MST1_TX_PIN;
extern const char HAL_I2S_MST1_TX_PIN_M_GPIO;
extern const char HAL_I2S_MST1_TX_PIN_M_SPI_MST0_SIO2;
extern const char HAL_I2S_MST1_TX_PIN_M_I2S_MST1_TX;
extern const char HAL_I2S_MST1_TX_PIN_M_UART0_RTS;
extern const char HAL_I2S_MST1_TX_PIN_M_I2S_SLV0_CK;
extern const char HAL_I2S_MST1_TX_PIN_M_I2C0_SDA;
extern const char HAL_I2S_MST1_TX_PIN_M_UART1_RTS;
extern const char HAL_I2S_MST1_TX_PIN_M_GPIO_PIP_SEL_1;
extern const char HAL_I2S_MST1_TX_PIN_M_DMIC1_DAT;
extern const char HAL_I2S_MST1_TX_PIN_M_PWM6;
extern const char HAL_I2S_MST1_TX_PIN_M_EINT;
extern const char HAL_I2S_MST1_TX_PIN_M_DEBUGMON14;
extern const char HAL_I2S_MST1_TX_PIN_M_usb_xcvr_sel0;


extern const char HAL_I2S_MST1_CK_PIN;
extern const char HAL_I2S_MST1_CK_PIN_M_GPIO;
extern const char HAL_I2S_MST1_CK_PIN_M_SPI_MST0_SIO3;
extern const char HAL_I2S_MST1_CK_PIN_M_I2S_MST1_CK;
extern const char HAL_I2S_MST1_CK_PIN_M_UART0_CTS;
extern const char HAL_I2S_MST1_CK_PIN_M_SPDIF;
extern const char HAL_I2S_MST1_CK_PIN_M_I2C0_SCL;
extern const char HAL_I2S_MST1_CK_PIN_M_UART1_CTS;
extern const char HAL_I2S_MST1_CK_PIN_M_BT_EPA_ELNA_CPS;
extern const char HAL_I2S_MST1_CK_PIN_M_GPIO_PIP_SEL_2;
extern const char HAL_I2S_MST1_CK_PIN_M_DMIC1_CLK;
extern const char HAL_I2S_MST1_CK_PIN_M_PWM7;
extern const char HAL_I2S_MST1_CK_PIN_M_EINT;
extern const char HAL_I2S_MST1_CK_PIN_M_DEBUGMON15;
extern const char HAL_I2S_MST1_CK_PIN_M_usb_xcvr_sel1;


extern const char HAL_I2C_MASTER_1_SDA_PIN;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_GPIO;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_SPI_MST0_CS0;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_I2S_MST0_MCLK;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_UART1_RXD;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_UART2_RXD;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_I2C1_SDA;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_SPI_MST0_SIO2;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_BT_EPA_ELNA_CRX;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_GPIO_PIP_SEL_3;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_DMIC0_DAT;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_AP_JTMS;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_EINT;
extern const char HAL_I2C_MASTER_1_SDA_PIN_M_DEBUGMON0;


extern const char HAL_I2C_MASTER_1_SCL_PIN;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_GPIO;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_SPI_MST0_CS1;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_I2S_MST0_TX;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_UART1_TXD;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_UART2_TXD;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_I2C1_SCL;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_SPI_MST0_SIO3;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_BT_EPA_ELNA_CTX;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_AUDIO_EXT_SYNC_EN1;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_DMIC0_CLK;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_PWM8;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_EINT;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_DEBUGMON1;
extern const char HAL_I2C_MASTER_1_SCL_PIN_M_usb_dm_pull_down;


extern const char HAL_UART2_RXD_PIN;
extern const char HAL_UART2_RXD_PIN_M_GPIO;
extern const char HAL_UART2_RXD_PIN_M_SPI_MST0_MISO;
extern const char HAL_UART2_RXD_PIN_M_I2S_MST0_WS;
extern const char HAL_UART2_RXD_PIN_M_UART1_RXD;
extern const char HAL_UART2_RXD_PIN_M_I2S_SLV0_WS;
extern const char HAL_UART2_RXD_PIN_M_I2C1_SDA;
extern const char HAL_UART2_RXD_PIN_M_BT_EPA_ELNA_CSD;
extern const char HAL_UART2_RXD_PIN_M_COEX_W3_BT_WLAN;
extern const char HAL_UART2_RXD_PIN_M_UART2_RXD;
extern const char HAL_UART2_RXD_PIN_M_DMIC1_DAT;
extern const char HAL_UART2_RXD_PIN_M_AUDIO_EXT_SYNC_EN0;
extern const char HAL_UART2_RXD_PIN_M_EINT;
extern const char HAL_UART2_RXD_PIN_M_DEBUGMON4;
extern const char HAL_UART2_RXD_PIN_M_usb_da_idpullup;


extern const char HAL_UART2_TXD_PIN;
extern const char HAL_UART2_TXD_PIN_M_GPIO;
extern const char HAL_UART2_TXD_PIN_M_SPI_MST0_MOSI;
extern const char HAL_UART2_TXD_PIN_M_I2S_MST0_RX;
extern const char HAL_UART2_TXD_PIN_M_UART1_TXD;
extern const char HAL_UART2_TXD_PIN_M_I2S_SLV0_RX;
extern const char HAL_UART2_TXD_PIN_M_I2C1_SCL;
extern const char HAL_UART2_TXD_PIN_M_BT_EPA_ELNA_ANT_SEL;
extern const char HAL_UART2_TXD_PIN_M_COEX_W3_BT_ACT;
extern const char HAL_UART2_TXD_PIN_M_UART2_TXD;
extern const char HAL_UART2_TXD_PIN_M_DMIC1_CLK;
extern const char HAL_UART2_TXD_PIN_M_AUDIO_EXT_SYNC_EN1;
extern const char HAL_UART2_TXD_PIN_M_EINT;
extern const char HAL_UART2_TXD_PIN_M_DEBUGMON5;
extern const char HAL_UART2_TXD_PIN_M_usb_drvvbus;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

extern const char HAL_UART0_DTE_DCD_PIN;
extern const char HAL_UART0_DTE_DSR_PIN;
extern const char HAL_UART0_DTE_DTR_PIN;
extern const char HAL_UART0_DTE_RI_PIN;
extern const char HAL_UART1_DTE_DCD_PIN;
extern const char HAL_UART1_DTE_DSR_PIN;
extern const char HAL_UART1_DTE_DTR_PIN;
extern const char HAL_UART1_DTE_RI_PIN;
extern const char HAL_UART2_DTE_DCD_PIN;
extern const char HAL_UART2_DTE_DSR_PIN;
extern const char HAL_UART2_DTE_DTR_PIN;
extern const char HAL_UART2_DTE_RI_PIN;
extern const char BSP_CTP_SW_I2C_SCL_PIN;
extern const char BSP_CTP_SW_I2C_SDA_PIN;
extern const char BSP_CTP_RST_PIN;
extern const char BSP_CTP_EINT_PIN;
extern const char BSP_SPEAKER_EBABLE_PIN;
extern const char BSP_AUXADC_ENABLE_PIN;
extern const char BSP_GNSS_POWER_PIN;
extern const char BSP_BIO_SENSOR_PPG_VDRV_EN;
extern const char BSP_BIO_SENSOR_32K;
extern const char BSP_BIO_SENSOR_RST_PORT_PIN;
extern const char BSP_BIO_SENSOR_AFE_PWD_PIN;
extern const char BSP_WIFI_32K_PIN;
extern const char BSP_WIFI_26M_PIN;
extern const char BSP_WIFI_RESET_PIN;
extern const char BSP_WIFI_ENABLE_PIN;
extern const char BSP_HP_ANA_SW_PIN;
extern const char UPDATE_HOST_STATUS_PIN;
extern const char QUERY_MODEM_STATUS_PIN;
extern const char NOTIFY_MODEM_EXCEPTION_PIN;
extern const char TRIGGER_MODEM_RESET_PIN;
extern const char NOTIFY_MODEM_WAKEUP_PIN;
extern const char TRIGGER_MODEM_START_PIN;
extern const char TRIGGER_MODEM_WAKEUP_PIN;
extern const char EXT_NTC_POWER_SW_PIN;
extern const char EXT_NTC_ADC_PIN;
extern const char EXT_DSP_POWER_SW_PIN;
extern const char EXT_DSP_CLK_SW_PIN;
extern const char EXT_DSP_RTC_CLK_SW_PIN;
extern const char EXT_DSP_32K_CLK_PIN;
extern const char NOTIFY_EXT_DSP_IRQ_PIN;
extern const char BSP_LED0_PIN;
extern const char BSP_LED1_PIN;
extern const char BSP_LED2_PIN;
extern const char BSP_GSENSOR_KEY_PIN;
extern const char BSP_LINE_IN_DET_PIN;
extern const char BSP_LINE_IN_SWITCH_PIN;
extern const char BSP_DETACHABLE_MIC_DET_PIN;
extern const char BSP_IRSENSOR_KEY_PIN;
extern const char BSP_ROTARY_ENCODER0_PIN_A;
extern const char BSP_ROTARY_ENCODER0_PIN_B;
extern const char BSP_ROTARY_ENCODER1_PIN_A;
extern const char BSP_ROTARY_ENCODER1_PIN_B;
extern const char BSP_ROTARY_ENCODER2_PIN_A;
extern const char BSP_ROTARY_ENCODER2_PIN_B;
extern const char BSP_PSENSOR_KEY_EVENT_NOTIFY_PIN;
extern const char BSP_PSENSOR_KEY_POWER_PIN;
extern const char BSP_DUAL_CHIP_TRIGGER_WAKEUP_PIN;
extern const char BSP_DUAL_CHIP_TRIGGER_RESET_PIN;
extern const char BSP_DUAL_CHIP_TRIGGER_POWER_KEY_PIN;


extern const char HAL_I2C_MASTER_0_SCL_PIN;
extern const char HAL_I2C_MASTER_0_SDA_PIN;
extern const char HAL_I2C_MASTER_2_SCL_PIN;
extern const char HAL_I2C_MASTER_2_SDA_PIN;
extern const char HAL_I2C_AO_SCL_PIN;
extern const char HAL_I2C_AO_SDA_PIN;
extern const char HAL_AUXADC_1_PIN;
extern const char HAL_AUXADC_2_PIN;
extern const char HAL_AUXADC_3_PIN;
extern const char HAL_AUXADC_4_PIN;
extern const char HAL_AUXADC_5_PIN;
extern const char HAL_AUXADC_6_PIN;
extern const char HAL_AUXADC_7_PIN;
extern const char HAL_MSDC_0_CK_PIN;
extern const char HAL_MSDC_0_CK1_PIN;
extern const char HAL_MSDC_0_CK2_PIN;
extern const char HAL_MSDC_0_CM_PIN;
extern const char HAL_MSDC_0_DA0_PIN;
extern const char HAL_MSDC_0_DA1_PIN;
extern const char HAL_MSDC_0_DA2_PIN;
extern const char HAL_MSDC_0_DA3_PIN;
extern const char HAL_PWM_0_PIN;
extern const char HAL_PWM_1_PIN;
extern const char HAL_PWM_2_PIN;
extern const char HAL_PWM_3_PIN;
extern const char HAL_PWM_4_PIN;
extern const char HAL_PWM_5_PIN;
extern const char HAL_PWM_6_PIN;
extern const char HAL_PWM_7_PIN;
extern const char HAL_PWM_8_PIN;
extern const char HAL_PWM_9_PIN;
extern const char HAL_UART0_RTS_PIN;
extern const char HAL_UART0_CTS_PIN;
extern const char HAL_UART1_TXD_PIN;
extern const char HAL_UART1_RTS_PIN;
extern const char HAL_UART1_CTS_PIN;
extern const char HAL_SPI_MASTER0_CS0_PIN;
extern const char HAL_SPI_MASTER0_CS1_PIN;
extern const char HAL_SPI_MASTER0_CS2_PIN;
extern const char HAL_SPI_MASTER0_CS3_PIN;
extern const char HAL_SPI_MASTER0_SCK_PIN;
extern const char HAL_SPI_MASTER0_MISO_PIN;
extern const char HAL_SPI_MASTER0_MOSI_PIN;
extern const char HAL_SPI_MASTER0_SIO2_PIN;
extern const char HAL_SPI_MASTER0_SIO3_PIN;
extern const char HAL_SPI_MASTER1_CS0_PIN;
extern const char HAL_SPI_MASTER1_CS1_PIN;
extern const char HAL_SPI_MASTER1_CS2_PIN;
extern const char HAL_SPI_MASTER1_CS3_PIN;
extern const char HAL_SPI_MASTER1_SCK_PIN;
extern const char HAL_SPI_MASTER1_MISO_PIN;
extern const char HAL_SPI_MASTER1_MOSI_PIN;
extern const char HAL_SPI_MASTER1_SIO2_PIN;
extern const char HAL_SPI_MASTER1_SIO3_PIN;
extern const char HAL_SPI_MASTER2_CS0_PIN;
extern const char HAL_SPI_MASTER2_CS1_PIN;
extern const char HAL_SPI_MASTER2_CS2_PIN;
extern const char HAL_SPI_MASTER2_CS3_PIN;
extern const char HAL_SPI_MASTER2_SCK_PIN;
extern const char HAL_SPI_MASTER2_MISO_PIN;
extern const char HAL_SPI_MASTER2_MOSI_PIN;
extern const char HAL_SPI_MASTER2_SIO2_PIN;
extern const char HAL_SPI_MASTER2_SIO3_PIN;
extern const char HAL_SPI_SLV0_CS_PIN;
extern const char HAL_SPI_SLV0_SCK_PIN;
extern const char HAL_SPI_SLV0_MISO_PIN;
extern const char HAL_SPI_SLV0_MOSI_PIN;
extern const char HAL_SPI_SLV0_SIO2_PIN;
extern const char HAL_SPI_SLV0_SIO3_PIN;
extern const char HAL_I2S_MST0_CK_PIN;
extern const char HAL_I2S_MST0_MCLK_PIN;
extern const char HAL_I2S_MST0_RX_PIN;
extern const char HAL_I2S_MST0_TX_PIN;
extern const char HAL_I2S_MST0_WS_PIN;
extern const char HAL_I2S_MST2_CK_PIN;
extern const char HAL_I2S_MST2_MCLK_PIN;
extern const char HAL_I2S_MST2_RX_PIN;
extern const char HAL_I2S_MST2_TX_PIN;
extern const char HAL_I2S_MST2_WS_PIN;
extern const char HAL_I2S_MST3_CK_PIN;
extern const char HAL_I2S_MST3_MCLK_PIN;
extern const char HAL_I2S_MST3_RX_PIN;
extern const char HAL_I2S_MST3_TX_PIN;
extern const char HAL_I2S_MST3_WS_PIN;
extern const char HAL_I2S_SLV0_CK_PIN;
extern const char HAL_I2S_SLV0_RX_PIN;
extern const char HAL_I2S_SLV0_TX_PIN;
extern const char HAL_I2S_SLV0_WS_PIN;
extern const char HAL_I2S_SLV1_CK_PIN;
extern const char HAL_I2S_SLV1_RX_PIN;
extern const char HAL_I2S_SLV1_TX_PIN;
extern const char HAL_I2S_SLV1_WS_PIN;
extern const char HAL_I2S_SLV2_CK_PIN;
extern const char HAL_I2S_SLV2_RX_PIN;
extern const char HAL_I2S_SLV2_TX_PIN;
extern const char HAL_I2S_SLV2_WS_PIN;
extern const char HAL_I2S_SLV3_CK_PIN;
extern const char HAL_I2S_SLV3_RX_PIN;
extern const char HAL_I2S_SLV3_TX_PIN;
extern const char HAL_I2S_SLV3_WS_PIN;


/*Output for SmartCharger variable names*/
extern const char HAL_UART0_RXD_PIN_M_UART0_TXD;
extern const char HAL_UART1_TXD_PIN_M_GPIO;
extern const char HAL_UART1_TXD_PIN_M_UART1_TXD;





