/* Copyright Statement:
 *
 * (C) 2021  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */


#ifndef __BSP_PSENSOR_KEY_CUSTOM_H__
#define __BSP_PSENSOR_KEY_CUSTOM_H__

// #define BSP_PSENSOR_KEY_USED_EPT_CONFIGURATION
// #define BSP_PSENSOR_KEY_TIMING_DEBUG_ENABLE

#define BSP_PSENSOR_KEY_EVENT_NOTIFY_PIN_NUM        HAL_GPIO_16;
#define BSP_PSENSOR_KEY_EVENT_NOTIFY_PIN_EINT_MODE  HAL_GPIO_16_EINT16;
#define BSP_PSENSOR_KEY_EVENT_NOTIFY_EINT_NUM       HAL_EINT_NUMBER_16;

#ifdef AIR_PSENSOR_KEY_POWER_PIN_ENABLE
#define BSP_PSENSOR_KEY_POWER_PIN_ENABLE
#define BSP_PSENSOR_KEY_POWER_PIN_NUM      HAL_GPIO_13
#endif

#ifndef BSP_PSENSOR_KEY_USED_EPT_CONFIGURATION
#define BSP_PSENSOR_KEY_I2C_SCL_PIN        HAL_GPIO_10
#define BSP_PSENSOR_KEY_I2C_SDA_PIN        HAL_GPIO_11
#define BSP_PSENSOR_KEY_I2C_SCL_PIN_MODE   HAL_GPIO_10_I2C1_SCL
#define BSP_PSENSOR_KEY_I2C_SDA_PIN_MODE   HAL_GPIO_11_I2C1_SDA
#endif

#endif //__BSP_PSENSOR_KEY_CUSTOM_H__

