/*
 * Generated by Airoha Easy PinMux Tool Version 2.8.1 for AB1585. Copyright Airoha Inc. (C) 2015.
 * 2022-05-11 13:30:05:0712
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
