/*
 * Generated by Airoha Easy PinMux Tool Version 2.7.5 for AB1585. Copyright Airoha Inc. (C) 2015.
 * 2021-11-29 16:07:21:0852
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
