/*
 * Generated by Airoha Easy PinMux Tool Version 2.9.7 for 1582P. Copyright Airoha Inc. (C) 2015.
 * 2023-01-31 10:14:57:0360
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

#ifndef  _EPT_EINT_DRV_H
#define  _EPT_EINT_DRV_H



#endif /* _EPT_EINT_DRV_H */
